alanmcgovern/monotorrent

src/MonoTorrent/MonoTorrent.Client/Peers/Peer.cs

Prevents Available peer count from fluctuating wildly after an announce.
peerId is not set for newly returned peers immediately after Announce() is called.
Previously, this resulted in equal peers being identified as different peers.
With this change, if peerId isn't set for EITHER old or new peer, comparison by host is performed.

Fix duplicate peer bug when peers first added after announce

---

src/MonoTorrent/MonoTorrent.Client/Managers/ConnectionManager.cs

There is no check yet to ensure that we do not connect to ourselves as a peer. In situations where there are few peers on the network for a large number of torrents, this could lead to a max connection count exhaustion although no downloading is actually occurring.
This patch first checks whether the engine’s listening address and port are the same as the peer’s and rejects such peers. In the case where the listening address is `IpAddr.Any`, it enumerates all IP addresses of all network devices that are up, and rejects the peer if it matches one of those addresses.

Do not try to connect to ourselves as a peer.

---

src/MonoTorrent/MonoTorrent.Common/SpeedMonitor.cs

Only update the lastUpdated value if we actually perform a update, otherwise if Tick() is called at a fixed rate lower than 800ms the internal average is never calculated. #53

Fix SpeedMonitor Tick() logic. Fixes slow peer download speed #53

---

src/MonoTorrent.Tests/Client/EndGamePickerTests.cs
src/MonoTorrent/MonoTorrent.Client/Managers/PeerExchangeManager.cs
src/MonoTorrent/MonoTorrent.Client/Modes/DownloadMode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/Mode.cs
src/MonoTorrent/MonoTorrent.Client/PeerConnections/PeerId.cs
src/MonoTorrent/MonoTorrent.Client/PiecePicking/EndGamePicker.cs
src/MonoTorrent/MonoTorrent.Client/PiecePicking/EndGameSwitcher.cs

@OneFingerCodingWarrior There was one leak where PeerIds would be retained forever in the StandardPicker when we swapped from `StandardPicker` -> `EndGamePicker`. There was a missing call to reset the StandardPicker when the swap occurred :)

Issue 102 fix leaks

---

src/MonoTorrent.Tests/Client/HttpTrackerTests.cs
src/MonoTorrent.Tests/Client/UdpTrackerTests.cs
src/MonoTorrent/MonoTorrent.BEncoding/BEncodedString.cs
src/MonoTorrent/MonoTorrent.Client.Connections/PeerId.cs
src/MonoTorrent/MonoTorrent.Client.Messages.UdpTracker/AnnounceMessage.cs
src/MonoTorrent/MonoTorrent.Client.Messages/HandshakeMessage.cs
src/MonoTorrent/MonoTorrent.Client.Tracker/AnnounceParameters.cs
src/MonoTorrent/MonoTorrent.Client.Tracker/HTTPTracker.cs
src/MonoTorrent/MonoTorrent.Client/ClientEngine.cs
src/MonoTorrent/MonoTorrent.Client/Managers/ConnectionManager.cs
src/MonoTorrent/MonoTorrent.Client/Managers/ListenManager.cs
src/MonoTorrent/MonoTorrent.Client/Modes/Mode.cs
src/MonoTorrent/MonoTorrent.Client/Peers/Peer.cs
src/MonoTorrent/MonoTorrent.Tracker.Listeners/UdpTrackerListener.cs
src/MonoTorrent/MonoTorrent.Tracker/AnnounceParameters.cs
src/MonoTorrent/MonoTorrent/PeerID.cs
src/MonoTorrent/MonoTorrent/VersionInfo.cs

This can be arbitrary bytes, but must be exactly 20 bytes in length.
As such we should treat it as a BEncodedString and not like ascii
text.

[core] Represent PeerID and TrackerID as a BEncodedString

---

src/MonoTorrent/MonoTorrent.Client/ClientEngine.cs

1st PR here. If there's something you'd like done differently, let me know.
The same peer id is always generated (`-MO1000-676515838224`) because `Random` is always seeded with 0 for the 1st `ClientEngine`. This prevents a monotorrent client from being able to connect to other monotorrent clients. Instead, set the 1st random seed randomly and increment from there for addition ClientEngines

Use a random seed for generating peer id

---

src/MonoTorrent.Tests/Client/FastResumeTests.cs
src/MonoTorrent.Tests/Client/TestWebSeed.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/HashingModeTests.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/InitialSeedingModeTest.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/StartingModeTests.cs
src/MonoTorrent/MonoTorrent.Client.PiecePicking/IgnoringPicker.cs
src/MonoTorrent/MonoTorrent.Client/FastResume/FastResume.cs
src/MonoTorrent/MonoTorrent.Client/Managers/DiskManager.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent/MonoTorrent.Client/Modes/HashingMode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/MetadataMode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/Mode.cs

Do not download

---

src/MonoTorrent.Tests/MonoTorrent.Client.Modes/DownloadModeTests.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent/MonoTorrent.Client/Modes/DownloadMode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/MetadataMode.cs
src/MonoTorrent/MonoTorrent/BitField.cs

When some files are marked as DoNotDownload then this property
tracks the completion rate for the files which are marked as
downloadable.
If all downloadable files have been downloaded, the state will
change to 'Seeding' without telling the tracker the download has
completed.
If files which used to be marked as 'DoNotDownload' are then marked
as downloadable, the state will change back to Downloading.

[core] Add a PartialProgress public property

---

src/MonoTorrent.Tests/Client/DiskManagerExceptionTests.cs
src/MonoTorrent.Tests/Client/DiskManagerTests.cs
src/MonoTorrent.Tests/Client/EncryptorFactoryTests.cs
src/MonoTorrent.Tests/Client/NetworkIOTests.cs
src/MonoTorrent.Tests/Client/PeerIOTests.cs
src/MonoTorrent.Tests/Client/SocketConnectionTests.cs
src/MonoTorrent.Tests/Client/TestRig.cs
src/MonoTorrent.Tests/Client/TestWebSeed.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/MetadataModeTests.cs
src/MonoTorrent.Tests/SocketStream.cs
src/MonoTorrent.Tests/TaskExtensions.cs
src/MonoTorrent/MonoTorrent.Client.Connections/ConnectionConverter.cs
src/MonoTorrent/MonoTorrent.Client.Connections/ConnectionFactory.cs
src/MonoTorrent/MonoTorrent.Client.Connections/HTTPConnection.cs
src/MonoTorrent/MonoTorrent.Client.Connections/IConnection2.cs
src/MonoTorrent/MonoTorrent.Client.Connections/PeerId.cs
src/MonoTorrent/MonoTorrent.Client.Connections/SocketConnection.cs
src/MonoTorrent/MonoTorrent.Client.Encryption/EncryptedSocket.cs
src/MonoTorrent/MonoTorrent.Client.Encryption/EncryptorFactory.cs
src/MonoTorrent/MonoTorrent.Client.Encryption/IEncryptor.cs
src/MonoTorrent/MonoTorrent.Client.Encryption/PeerAEncryption.cs
src/MonoTorrent/MonoTorrent.Client.Encryption/PeerBEncryption.cs
src/MonoTorrent/MonoTorrent.Client/EventArgs/NewConnectionEventArgs.cs
src/MonoTorrent/MonoTorrent.Client/Managers/ConnectionManager.cs
src/MonoTorrent/MonoTorrent.Client/Managers/DiskManager.cs
src/MonoTorrent/MonoTorrent.Client/Managers/ListenManager.cs
src/MonoTorrent/MonoTorrent.Client/NetworkIO.cs
src/MonoTorrent/MonoTorrent.Client/PeerIO.cs
src/MonoTorrent/MonoTorrent.csproj
src/MonoTorrent/System.Runtime.CompilerServices/AsyncVoidMethodBuilder.cs

Setup:
* Debug build
* Only peers on my local network are used, no internet based peers.
* Two 2GB torrents fully downloaded
Memory allocations before changes:
Memory allocations after changes:

Vastly reduce allocations from async/await infrastructure

---

src/MonoTorrent.Tests/Client/HttpTrackerTests.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/DownloadModeTests.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/HashingModeTests.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/StoppedModeTests.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/StoppingModeTests.cs
src/MonoTorrent/MonoTorrent.Client.Connections/PeerId.cs

This is in advance of adding sanity checks to the peer parsing
code to ensure we never accept peers which are missing a port.

[tests] Always set an IP and a port for Peer Uris

---

src/MonoTorrent/MonoTorrent.Client.Connections/SocketConnection.cs

If we are using a SocketAsyncEventArgs to wrap a buffer which
does not come from the pool, ensure we null out the buffer when
we finish with that invocation.
Allows the buffer to be GCed eventually.

[core] Do not cache old buffers longer than needed

---

src/MonoTorrent/MonoTorrent.Client.Messages/MutableRequestMessage.cs
src/MonoTorrent/MonoTorrent.Client.Messages/RequestBundle.cs
src/MonoTorrent/MonoTorrent.Client.Messages/RequestMessage.cs
src/MonoTorrent/MonoTorrent.Client/Managers/PieceManager.cs

Don't allocate a new list every time we pick a piece. We
can pass in the existing list exactly as-is.
Also, don't create one RequestMessage for every PieceRequest.
We can optimise the common case of having dozens of requests
by creating another type like MessageBundle, which can write
multiple requests into one buffer.

[core] Reduce allocations from PieceManager

---

src/MonoTorrent.Tests/Client/EndGamePickerTests.cs
src/MonoTorrent/MonoTorrent.Client.PiecePicking/EndGamePicker.cs

In endgame mode ensure that *all* pending requests for a given piece
are cancelled if/when every block for a piece has been received once.
This ensure that when the piece is hash checked, we will be able to
fully redownload all pieces if the hash check fails.

[core] Cancel all pending requests when the piece has been received

---

src/MonoTorrent/MonoTorrent.Client/ClientEngine.cs
src/MonoTorrent/MonoTorrent.Client/LocalPeerDiscovery.cs

The previous catch-all exception handling would enter an infinite loop when
for some reason ReusableTasks.dll was not properly deployed.

[core] Do not ignore FileNotFoundException when discovering local peers.

---

src/MonoTorrent.Tests/Client/TestRig.cs

This is an additional safety check to ensure logic internal to
the library never over-reads.

[tests] Ensure the TestWriter doesn't allow accidental overreads

---

src/MonoTorrent/MonoTorrent/TorrentCreator.cs

Allow 8MB pieces as a default maximum now, and also use
some constants to make it a little cleaner.

[core] Make auto piecelength detection a little nicer

---

src/MonoTorrent.Tests/Common/TorrentCreatorTests.cs
src/MonoTorrent/MonoTorrent.Client.PieceWriters/DiskWriter.cs
src/MonoTorrent/MonoTorrent.Client/FileStreamBuffer.cs
src/MonoTorrent/MonoTorrent/Synchronizer.cs
src/MonoTorrent/MonoTorrent/TorrentCreator.cs

After running `sudo purge` to simulate an uncached/unbuffered run on my Mac, the timings for a 2GB file are:
```
Total:             00:00:15.7296231
ReadAll - Dequeue: 00:00:14.5927816
ReadAll - Read:    00:00:00.9673251
ReadAll - Enqueue: 00:00:00.0158462
Hashing - Dequeue: 00:00:00.0528362
Hashing - Hashing: 00:00:15.3869370
Hashing - Enqueue: 00:00:00.1013505
```
A cached/buffered run looks like:
```
Total:             00:00:14.4390740
ReadAll - Dequeue: 00:00:13.9951740
ReadAll - Read:    00:00:00.4241805
ReadAll - Enqueue: 00:00:00.0078499
Hashing - Dequeue: 00:00:00.0075505
Hashing - Hashing: 00:00:14.3528456
Hashing - Enqueue: 00:00:00.0734906
```
The vast majority of the time is in the SHA1 hashing when we read from the disk in 256kB chunks using one thread.

Create torrents in parallel

---

src/MonoTorrent.Tests/Client/EndGamePickerTests.cs
src/MonoTorrent.Tests/Client/EndGameSwitcherTests.cs
src/MonoTorrent/MonoTorrent.Client.Connections/PeerId.cs
src/MonoTorrent/MonoTorrent.Client.PiecePicking/EndGameSwitcher.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs

Begin addressing https://github.com/mono/monotorrent/issues/183. The intention is to remove the hardcoded piece counts from endgame mode and instead adjust the logic so it more dynamically enters endgame based on the download speed and proportion of pieces which are remaining.
Currently we enter endgame mode when fewer than 20 blocks are left to download . This should really be something a little more dynamic like "As soon as all blocks have been requested" or "As soon as the majority of peers which have unchoked us are not having blocks allocated to them for download".

Improve the endgame switcher logic

---

src/MonoTorrent.Tests/Client/TestRig.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/DownloadModeTests.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/HashingModeTests.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/StartingModeTests.cs
src/MonoTorrent/MonoTorrent.Client.Connections/PeerId.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent/MonoTorrent.Client/Modes/ErrorMode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/HashingMode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/MetadataMode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/Mode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/StartingMode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/StoppedMode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/StoppingMode.cs

If a user calls 'StartAsync' and then invokes it a second time
without awaiting the original 'Task' we will now throw an
exception. This is not supported!

[core] Calling 'StartAsync' twice concurrently is an error

---

src/MonoTorrent/MonoTorrent.Client/Managers/ConnectionManager.cs

Before we allow a peer to be added to the 'Connected' list,
ensure it's bitfield is of the correct length.
If we were in metadata mode before handshaking occurred and
we're in regular mode after it occurs, we could be left
with a peer with an incorrect bitfield.
Addresses https://github.com/mono/monotorrent/issues/196

[core] Sanity check the bitfield length when connecting

---

src/MonoTorrent.Tests/MonoTorrent.Client.Modes/DownloadModeTests.cs
src/MonoTorrent/MonoTorrent.Client/Managers/ConnectionManager.cs
src/MonoTorrent/MonoTorrent.Client/Managers/PeerManager.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs

Once a connection has been established to a remote peer, or
an incoming connection has been received, we should add the
peer to the 'Connected' list.
This way any logic which attempts to close all open connections
will successfully close connections which are still completing
the normal bittorrent handshake.

[core] Don't special case peers which are handshaking

---

src/MonoTorrent.Tests/Client/TestRig.cs
src/MonoTorrent.Tests/Common/TorrentCreatorTests.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/MetadataModeTests.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent/MonoTorrent.Client/Modes/MetadataMode.cs

fixes mono/monotorrent#209
also fixes small typos in TorrentCreatorTests

Fixed multifile metadatamode savepath handling, fixes mono/monotorrent#209

---

src/MonoTorrent.Tests/Common/PathValidatorTests.cs
src/MonoTorrent.Tests/Common/TorrentTest.cs
src/MonoTorrent/MonoTorrent/PathValidator.cs
src/MonoTorrent/MonoTorrent/Torrent.cs
src/MonoTorrent/MonoTorrent/TorrentCreator.cs

Ensure path traversal attacks are prevented by disallowing
torrents with embedded path traversals. The logic is shared
between TorrentCreator and Torrent so the same validations
are performed when loading or creating torrents.

[core] Add path validation when loading torrents

---

src/MonoTorrent.Tests/Client/ManualTrackerManager.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/StoppingModeTests.cs
src/MonoTorrent/MonoTorrent.Client/ClientEngine.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent/MonoTorrent.Client/Modes/StoppingMode.cs

This allows a relatively simple override for the final announce
so that the returned task doesn't hang around forever.
This is not implemented in the best of ways. Ideally the
ITracker and ITrackerManager interfaces would be augmented
to take a CancellationToken or TimeSpan parameter to handle
cancellation/timeouts, but that would be an ABI break which
I don't want to do right now.
This approach isn't great as it doesn't actually cancel the
pending request, but it's good enough and allows people to
use the timeout functionality in a way which will be
compatible with any future changes to ITracker/ITrackerManager.

[core] Add a timeout when stopping torrents

---

src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent/MonoTorrent.Client/Modes/StartingMode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/StoppingMode.cs
src/MonoTorrent/MonoTorrent.Client/Peers/Peer.cs

We no longer clear the peer list when stopping
a torrent manager. Instead the peers are marked
as 'MaybeStale' the next time the manager is
started. We will connect to those as normal, but
if an announce occurs and we get new peers, we'll
replace any peers which are marked a 'MaybeStale'
with fresh ones which are more likely to be online.
Addresses https://github.com/alanmcgovern/monotorrent/issues/221

[core] Retain peers when restarting torrents

---

src/MonoTorrent.Tests/Common/IListExtensionsTests.cs
src/MonoTorrent/MonoTorrent.Client.PiecePicking/StandardPicker.cs
src/MonoTorrent/MonoTorrent.Client/Managers/DiskManager.cs
src/MonoTorrent/MonoTorrent/IListExtensions.cs

These overloads allow passing a state object, which
means we can pass a ValueTuple and have allocation-free
binary searching when we need to use local method state
to find the location we care about.
Thanks to @therzok for pushing me to do it ;)

[core] Add allocation-free BinarySearch overloads

---

src/MonoTorrent.Tests/Client/PriorityPickerTests.cs
src/MonoTorrent/MonoTorrent.Client.PiecePicking/EndGameSwitcher.cs
src/MonoTorrent/MonoTorrent.Client.PiecePicking/PriorityPicker.cs
src/MonoTorrent/MonoTorrent/BitField.cs
src/MonoTorrent/MonoTorrent/TorrentFile.cs

Rather than storing one bitfield per TorrentFile just
to represent the start/end piece, we can use a simple
ValueTuple. The bitfield is used as a selector to
simplify some operations, but a ValueTuple representing
the (inclusive) start/end piece can perform the same
job.
The typical usecase is when some files are marked as
'DoNotDownload' and the selector is used to exclude
those pieces in the PiecePicker.

[core] Optimise memory for TorrentFile

---

src/MonoTorrent/MonoTorrent.Client.PiecePicking/PriorityPicker.cs
src/MonoTorrent/MonoTorrent.Client.PiecePicking/StandardPicker.cs
src/MonoTorrent/MonoTorrent.Client/Managers/DiskManager.cs
src/MonoTorrent/MonoTorrent/BitField.cs
src/MonoTorrent/MonoTorrent/TorrentFile.cs

It allows naming the various parameters, which makes
it much easier to consume tuples throughout the codebase.
Suggestion from Therzok.

[core] Prefer named tuple syntax over ValueTuple

---

src/MonoTorrent/MonoTorrent.Client.Tracker/HTTPTracker.cs

The profiler shows these as being potentially slow operations,
so ensure we bounce them to the threadpool so the synchronous
aspect of WebRequest.Create (and WebRequest itself) has no
impact on the main thread.
Partially address https://github.com/alanmcgovern/monotorrent/issues/223

[core] Move some Web operations to the threadpool

---

src/MonoTorrent.Tests/MonoTorrent.Client.Modes/HashingModeTests.cs
src/MonoTorrent/MonoTorrent.Client/EventArgs/PieceHashedEventArgs.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent/MonoTorrent.Client/Modes/DownloadMode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/HashingMode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/Mode.cs

Users can tell how complete the hashing progress is. This takes
into account the fact that files which are marked as
DoNotDownload will not be hashed.
Fixes https://github.com/alanmcgovern/monotorrent/issues/180

[core] Add a progress counter when hashing

---

src/MonoTorrent/MonoTorrent.Client.Encryption/EncryptedSocket.cs
src/MonoTorrent/MonoTorrent.Client.Encryption/EncryptorFactory.cs
src/MonoTorrent/MonoTorrent.Client.Encryption/PeerAEncryption.cs
src/MonoTorrent/MonoTorrent.Client.Encryption/PeerBEncryption.cs

Push all the socket crypto work to a background thread.
While it's not a lot of CPU time, it's still stuff which
should be executed on the threadpool so the main loop is
available for syncing, and also to handle things like
StopAsync/StartAsync etc.
Partially addresses https://github.com/alanmcgovern/monotorrent/issues/223

[core] Ensure crypto is not on the engine thread

---

src/MonoTorrent/MonoTorrent.Client.Tracker/HTTPTracker.cs
src/MonoTorrent/MonoTorrent.Client.Tracker/UdpTracker.cs
src/MonoTorrent/MonoTorrent/Enums.cs

Add an 'Unknown' state to represent when we haven't
sent an announce or scrape request to a tracker yet.
Add a 'Connecting' state to represent when we're
sending an Announce or Scrape request.
NOTE: There's the potential for trampling here as
the Announce and Scrape codepaths both write to
the same 'FailureMessage', 'WarningMessage' and
'State' variables. Fixing this will be an API
break.
Fixes https://github.com/alanmcgovern/monotorrent/issues/255

[core] Add two states to the TrackerState enum

---

src/MonoTorrent.Tests/Streaming/StreamProviderTests.cs
src/MonoTorrent/MonoTorrent.Client/ClientEngine.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent/MonoTorrent.Client/Modes/MetadataMode.cs
src/MonoTorrent/MonoTorrent.Streaming/StreamProvider.cs

StreamProvider can only work when we know which file
needs to be streamed. Add a simple way for users to wait
for the metadata to be downloaded, taking into account the
existence of cached versions of the metadata.
This also exposes a 'Files' property so there is ready
access to the piece of information we need to get a
local or http stream.

[core] Add the ability to wait for metadata to download

---

src/MonoTorrent.Tests/Streaming/StreamProviderTests.cs
src/MonoTorrent/MonoTorrent.Streaming/StreamProvider.cs

Ensure we download the first and last pieces before giving the user
the Stream. This means a streaming player can (probably) play
without buffering/stuttering.
Prebuffering can be turned off if needed by passing 'false' to
the correct CreateStream overload.

[core] Add prebuffering and CancellationTokens to StreamProvider

---

src/MonoTorrent.Tests/Client/ChokeUnchokeManagerTests.cs
src/MonoTorrent/MonoTorrent.Client.Connections/PeerId.cs
src/MonoTorrent/MonoTorrent.Client/ClientEngine.cs
src/MonoTorrent/MonoTorrent.Client/Managers/ChokeUnchokeManager.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent/MonoTorrent.Client/Modes/Mode.cs
src/MonoTorrent/MonoTorrent.Client/Settings/TorrentSettings.cs
src/MonoTorrent/MonoTorrent.Client/Unchokers/IUnchokeable.cs
src/MonoTorrent/MonoTorrent.Client/Unchokers/TorrentManagerUnchokeable.cs

Fixes some issues with ChokeUnchokeManager.
Firstly, to aid testing, I wrapped TorrentManager in an `IUnchokeable` interface. This lets me mock up the appropriate objects so I can exercise the various parts of the unchoker logic much more easily!
As part of this I removed the old checks for `Connection == null` because this is literally impossible (it's a readonly property) nowadays.
I then fixed the issue where settings UploadSlots to zero would result in no peers being unchoked when we actually want *all* peers to be unchoked.

Upload slots

---

src/MonoTorrent.Tests/Client/ChokeUnchokeManagerTests.cs
src/MonoTorrent/MonoTorrent.Client/Managers/ChokeUnchokeManager.cs
src/MonoTorrent/MonoTorrent.Client/Peers/PeerList.cs
src/MonoTorrent/MonoTorrent.Client/Unchokers/IUnchokeable.cs
src/MonoTorrent/MonoTorrent.Client/Unchokers/TorrentManagerUnchokeable.cs
src/MonoTorrent/MonoTorrent/ValueStopwatch.cs

Greatly simplify the code in ChokeUnchokeManager. We now run a review every `minimumTimeBetweenReviews` even if we currently have enough free slots
to unchoke all currently interested peers.
The need to track `firstCall` and `isDownloading` was removed. `firstCall` is
unnecessary as we already track 'time since last review' and know when
we have *never* run a review. isDownloading is unnecessary as we used
it to trigger a review when the torrentmanager goes from downloading
to seeding - we handle that case by resetting the timer for the last
review so we execute  a review on the next iteration.

[core] Clean up more code from the Unchoker

---

src/MonoTorrent.Tests/MonoTorrent.Client.Modes/DownloadModeTests.cs
src/MonoTorrent/MonoTorrent.Client/Modes/DownloadMode.cs

… it sends multiple TorrentStateChanged events during download

Fix for DownloadMode.UpdateSeedingDownloadingState logic

---

src/MonoTorrent.Tests/MonoTorrent.Client.Modes/MetadataModeTests.cs
src/MonoTorrent/MonoTorrent.Client.Messages/BitfieldMessage.cs
src/MonoTorrent/MonoTorrent.Client.Messages/PeerMessage.cs
src/MonoTorrent/MonoTorrent.Client/Modes/InitialSeedingMode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/MetadataMode.cs
src/MonoTorrent/MonoTorrent/ITorrentData.cs

We should ignore them when they're received. This is
implemented by special casing the situation where a
BitfieldMessage is received while we do not have
metadata - in this scenario we return the special value
'BitfieldMessage.UnknownValue' which we can check for
later.
If we attempt to *send* this to a peer it will error
out when you invoke 'Encode'. The MetadataMode overload
for 'HandleBitfield' asserts that all bitfields were
decoded as this sentinal value.
Before this patch we could only retrieve metadata from
peers which have no data, or from seeders. With this
patch we can download metadata from leechers too.

[core] Properly handle bitfield messages in metadata mode

---

src/MonoTorrent.Tests/Client/PieceManagerTests.cs
src/MonoTorrent.Tests/Client/TestRig.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/MetadataModeTests.cs
src/MonoTorrent/MonoTorrent.Client/Managers/ConnectionManager.cs
src/MonoTorrent/MonoTorrent.Client/Managers/ListenManager.cs
src/MonoTorrent/MonoTorrent.Client/Managers/PieceManager.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent/MonoTorrent.Client/Modes/Mode.cs

Ensure we close connections for all PeerIds when swapping between MetadataMode and regular mode.

Fix metadata mode transition

---

src/MonoTorrent/MonoTorrent.Client/LocalPeerDiscovery.cs

The description of a problem is [here](https://github.com/alanmcgovern/monotorrent/issues/322)

issue#322 Using MulticastIpAddress instead of IPAddress.Broadcast for initializing UdpClient in LPD

---

src/MonoTorrent/MonoTorrent.Client.PortForwarding/MonoNatPortForwarder.cs
src/MonoTorrent/MonoTorrent.csproj

App is crashing after Mono.Nat was updated. Previous implementation had a DeviceLost event, that is was removed.
Exception: System.MissingMethodException: Method not found: 'Void Mono.Nat.NatUtility.add_DeviceLost(System.EventHandler`1<Mono.Nat.DeviceEventArgs>)'.

Mono.Nat package update fix.

---

src/MonoTorrent/MonoTorrent.Client/Managers/DiskManager.cs

Moving files of even a stopped torrent will crash if a file does not yet exist. This checks for existence first and does not move the not existing file.

Fix moving unfinished, stopped torrent.

---

src/MonoTorrent.Tests/MonoTorrent.Client.Modes/MetadataModeTests.cs
src/MonoTorrent/MonoTorrent.Client/Modes/MetadataMode.cs

Firstly, don't reset the stream every time we connect
to a peer who supports metadata mode. That's... silly.
Secondly, once we get the validated metadata we should
emit the 'MetadataReceived' event and bail.
Thirdly, once we have validated metadata we can safely
ignore any freshly received LTMetadata messages as we
know the data is no longer needed.
Each of these changes deserves a test :p

[core] Fix a couple of additional metadatamode races

---

src/MonoTorrent.Tests/Common/BEncodingTest.cs
src/MonoTorrent/MonoTorrent.BEncoding/BEncodeDecoder.cs
src/MonoTorrent/MonoTorrent.BEncoding/BEncodedDictionary.cs
src/MonoTorrent/MonoTorrent.BEncoding/RawReader.cs
src/MonoTorrent/MonoTorrent.Client/Modes/MetadataMode.cs
src/MonoTorrent/MonoTorrent/Torrent.cs

If a BEncodedDictionary has been encoded with the keys in the
wrong order, we will now compute the infohash based on the
underlying bytes. This is the other spec compliant approach.
The first spec compliant approach is to reject the torrent.
Unfortunately there are plenty of invalid torrents out there,
so at this stage we may as well do the work to support this.
This should not be any worse performance wise as the original
approach.
Solves https://github.com/alanmcgovern/monotorrent/issues/332

[core] Compute the correct infohash for misordered dictionaries

---

src/MonoTorrent.Tests/Client/DiskWriterTests.cs
src/MonoTorrent/MonoTorrent.Client/FileStreamBuffer.cs
src/MonoTorrent/MonoTorrent.Client/MainLoop.cs
src/MonoTorrent/MonoTorrent.Client/Managers/DiskManager.cs
src/MonoTorrent/MonoTorrent.Client/Managers/ITorrentFileInfo.cs

We should ensure we're executing on the IO thread
when we're interacting with the filestreams.
The 'Tick' method is invoked from the main engine's
tick so it'll be on the wrong thread unless we swap
here.
Also, ensure we take an async lock on the filestream
we intend to flush. This ensures there's multi-threaded
IO, but each stream is accessed in a single-threaded way.
Fixes https://github.com/alanmcgovern/monotorrent/issues/345

[core] Fix a threading issue in FlushAsync

---

src/MonoTorrent.Tests/Client/ManualStream.cs
src/MonoTorrent/MonoTorrent.Client/FileStreamBuffer.cs
src/MonoTorrent/MonoTorrent.Client/ITorrentFileStream.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentFileInfo.cs
src/MonoTorrent/MonoTorrent.Client/TorrentFileStream.cs
src/MonoTorrent/MonoTorrent/SemaphoreSlimExtensions.cs

This allocates far less than the built-in implementation
so it's a net win for monotorrent. The perf delta is
not detectable from a profiler.

[core] Swap to a more efficient SemaphoreSlim impl

---

src/MonoTorrent.Tests/Client/EndGameSwitcherTests.cs
src/MonoTorrent.Tests/Client/StandardPickerTests.cs
src/MonoTorrent/MonoTorrent.Client.PiecePicking/EndGamePicker.cs
src/MonoTorrent/MonoTorrent.Client.PiecePicking/EndGameSwitcher.cs
src/MonoTorrent/MonoTorrent.Client.PiecePicking/PiecePicker.cs
src/MonoTorrent/MonoTorrent.Client.PiecePicking/StandardPicker.cs
src/MonoTorrent/MonoTorrent.Client/Managers/PieceManager.cs

Now we only try to continue an existing request if the
peer has been unable to select one normally.
Additionally, we only continue other peer's pieces if
the peer in question has zero pending requests. This
is slightly inefficient in terms of pipelining, but
it's probably better that a peer finish it's queue of
up to 300-500 pieces *before* it starts stealing pieces
from other peers.

[core] Improve 'ContinueAnyExistingRequest'

---

src/MonoTorrent/MonoTorrent.Client/MainLoop.cs

Use two queues to allow tasks to be processed with
fewer locks.
By swapping the queue object we can dequeue every
message in the old queue object without needing
to take further locks. When the old queue is empty,
we can swap it again and start processing tasks
in the new queue.

[core] Lock fewer times when iterating the main loop

---

src/MonoTorrent.Tests/Client/StreamingPiecePickerTests.cs
src/MonoTorrent/MonoTorrent.Client.PiecePicking/StreamingPiecePicker.cs

If we seek to the same piece we're already in then we don't
need to cancel pending piece requests.

[core] Small optimisation to avoid excessive cancelling

---

src/MonoTorrent.Tests/MonoTorrent.Client.Modes/MetadataModeTests.cs
src/MonoTorrent/MonoTorrent.Client.Messages.Libtorrent/ExtendedHandshakeMessage.cs
src/MonoTorrent/MonoTorrent.Client/Modes/MetadataMode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/Mode.cs

If a peer does not send the 'MetadataSize' key it
means they do not have metadata to send us. We
cannot create the Stream using these peers as
we'd end up creating a Bitfield of length 0.
This can cause unusual NullReferenceExceptions
later on.

[core] Handle peers who do not have metadata yet

---

src/MonoTorrent.Tests/Client/StreamingPiecePickerTests.cs
src/MonoTorrent/MonoTorrent.Client.PiecePicking/StreamingPiecePicker.cs

Use a better prioritisation technique for streaming.
The very first piece in the high priority set must be 100% requested, in triplicate, before any other blocks are requested. The same rule applies to the second piece. The third and subsequent piece are requested from multiple peers, but are not requested in triplicate.

Better streaming

---

src/MonoTorrent.Tests/Client/DiskManagerExceptionTests.cs
src/MonoTorrent.Tests/Client/DiskManagerTests.cs
src/MonoTorrent.Tests/Client/DiskWriterTests.cs
src/MonoTorrent.Tests/Client/MemoryCacheTests.cs
src/MonoTorrent.Tests/Client/PieceManagerTests.cs
src/MonoTorrent.Tests/Client/PieceWriterExtensionTests.cs
src/MonoTorrent.Tests/Client/PriorityPickerTests.cs
src/MonoTorrent.Tests/Client/RandomisedPickerTests.cs
src/MonoTorrent.Tests/Client/RarestFirstPickerTests.cs
src/MonoTorrent.Tests/Client/StandardPickerTests.cs
src/MonoTorrent.Tests/Client/TestRig.cs
src/MonoTorrent.Tests/Common/TorrentTest.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/DownloadModeTests.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/HashingModeTests.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/StartingModeTests.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/StoppedModeTests.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/StoppingModeTests.cs
src/MonoTorrent/MonoTorrent.Client.PiecePicking/StreamingPieceRequester.cs
src/MonoTorrent/MonoTorrent.Client.PieceWriters/IPieceWriter.cs
src/MonoTorrent/MonoTorrent.Client/Managers/ITorrentFile.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentFileInfo.cs
src/MonoTorrent/MonoTorrent.Streaming/LocalStream.cs
src/MonoTorrent/MonoTorrent/ITorrentData.cs
src/MonoTorrent/MonoTorrent/Torrent.cs
src/MonoTorrent/MonoTorrent/TorrentCreator.cs
src/MonoTorrent/MonoTorrent/TorrentFile.cs

Now we can handle multiple consecutive zero length files while
retaining the new logic to binary search files either by offset
within the overall torrent, or by piece index.
As part of this the test suite has been updated to ensure it
always sets the start and end piece index correctly, and also
the offset within the torrent file.

[core] Fix how TorrentFile's are created

---

src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent/MonoTorrent.Client/Settings/TorrentSettings.cs
src/MonoTorrent/MonoTorrent.Client/Settings/TorrentSettingsBuilder.cs

Added CreateSubFolder property to TorrentSetting (if set to false root folder will be not created for multi-file torrent)
Usefull when MonoTorrent using in application as self-update engine.

Added CreateSubFolder property to TorrentSetting

---

src/MonoTorrent.Tests/Client/ClientEngineTests.cs
src/MonoTorrent.Tests/Client/TestRig.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/DownloadModeTests.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/MetadataModeTests.cs
src/MonoTorrent.Tests/Streaming/StreamProviderTests.cs
src/MonoTorrent/MonoTorrent.Client/ClientEngine.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent/MonoTorrent.Client/Settings/EngineSettings.cs
src/MonoTorrent/MonoTorrent.Client/Settings/EngineSettingsBuilder.cs
src/MonoTorrent/MonoTorrent.Client/Settings/TorrentSettings.cs
src/MonoTorrent/MonoTorrent.Client/Settings/TorrentSettingsBuilder.cs
src/MonoTorrent/MonoTorrent.Streaming/StreamProvider.cs
src/SampleClient/StressTest.cs
src/SampleClient/main.cs

Some simplifications to the API.
Rather than manually creating a torrent manager, then registering it, we can make this a single API call: `ClientEngine.AddAsync`
Similarly, rather than creating a StreamingProvider to set up a torrent for streaming access, you can now just call `ClientEngine.AddStreamingAsync`. This will populate the `TorrentManager.StreamProvider` property and you'll be able to get access to the files within the torrent while the torrent is actively downloading. 
As always, if you use `TorrentManager.StreamProvider` to create a stream you can treat it like a normal FileStream. If you call ReadAsync, SeekAsync, etc, the engine will automatically download the data required to fulfill your Read or Seek request.

Engine addremove

---

src/MonoTorrent.Tests/Client/FastResumeTests.cs
src/MonoTorrent.Tests/Client/TestRig.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/DownloadModeTests.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/HashingModeTests.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/MetadataModeTests.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/StartingModeTests.cs
src/MonoTorrent.Tests/Streaming/StreamProviderTests.cs
src/MonoTorrent.Tests/TaskExtensions.cs
src/MonoTorrent.Tests/TempDir.cs
src/MonoTorrent/MonoTorrent.Client/ClientEngine.cs
src/MonoTorrent/MonoTorrent.Client/FastResume/FastResume.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent/MonoTorrent.Client/Modes/DownloadMode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/HashingMode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/StartingMode.cs
src/MonoTorrent/MonoTorrent.Client/Settings/EngineSettings.cs
src/MonoTorrent/MonoTorrent.Client/Settings/EngineSettingsBuilder.cs
src/SampleClient/MagnetLinkStreaming.cs

The engine will now automatically save/load/delete fast resume
based on heuristics.
If a TorrentManager is loaded into the ClientEngine using the
new `AddAsync` or `AddStreamingAsync` methods then any
existing fast resume data will be implicitly loaded.
If a TorrentManager is started and it enters the *downloading*
mode, i.e. the only mode which mutates the torrent's state,
then any existing fast resume data will be implicitly deleted.
If a TorrentManager enters the 'Stopped' mode, and an error did
not occur, then new fast resume data will be saved to disk.
Implements most of https://github.com/alanmcgovern/monotorrent/issues/400

[core] Add support for automatically saving/loading FastResume

---

src/MonoTorrent/MonoTorrent.Client/ClientEngine.cs
src/MonoTorrent/MonoTorrent.Client/Settings/EngineSettings.cs

If the DhtEngine is implicitly managed by the engine then
it will now also implicitly manage saving/restore the list
of nodes when the DhtEngine is started/stopped.

[core] Auto save/restore dht nodes too

---

src/MonoTorrent/MonoTorrent.Streaming/HttpStream.cs
src/MonoTorrent/MonoTorrent.Streaming/StreamProvider.cs

The following changes add the ability to have CORS enabled on httplistener. So far, CORS Policy declined message goes away for HTML5 video player by viewing under Chrome. May need more work.

COR Policies added to HttpStream 

---

src/MonoTorrent/MonoTorrent.Client.PiecePicking/IPieceRequester.cs
src/MonoTorrent/MonoTorrent.Client.PiecePicking/StandardPieceRequester.cs
src/MonoTorrent/MonoTorrent.Client.PiecePicking/StreamingPieceRequester.cs
src/MonoTorrent/MonoTorrent.Client/Managers/PieceManager.cs

This parameter is unnecessary, and is also confusing. IPieceRequester
can calculate the correct bitfield to pass to the IPiecePicker impl
by starting with the pieces the peer actually has, and the removing
each piece in the 'ignoring' bitfields.

[core] Remove a parameter from IPieceRequester

---

src/MonoTorrent.Tests/Client/PieceManagerTests.cs
src/MonoTorrent.Tests/Client/PriorityPickerTests.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/DownloadModeTests.cs
src/MonoTorrent.Tests/MonoTorrent.Client.Modes/HashingModeTests.cs
src/MonoTorrent/MonoTorrent.Client.PiecePicking/PriorityPicker.cs
src/MonoTorrent/MonoTorrent.Client/Managers/ITorrentFileInfo.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent/MonoTorrent.Client/Modes/DownloadMode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/HashingMode.cs
src/MonoTorrent/MonoTorrent.Client/Modes/Mode.cs
src/MonoTorrent/MonoTorrent/TorrentCreator.cs

Don't allow people to set this directly via public API.
It's much more efficient for the library to handle updates
via an async method.
Firstly, it removes the race condition where the user could
be trying to update the priority while monotorrent is accesing
it. Accesses to this property have always had to be carefully
made as the value could change immediately after it was
read. Now these concerns are eliminated.
Secondly, it provides a convenient place to update some
state in the library. For example calculating partial progress,
and also when updating the priority based piece picker.

[core] Use a proper way to change file priority

---

src/MonoTorrent/MonoTorrent/BitField.cs

The 'BitField' class is supposed to be readonly in every scenario
where it's exposed to users.
After a fair bit of thinking, the best way to enforce this is to
make the mutating methods internal. This will allow the monotorrent
to update the bitfields as data is modified, while ensuring users
cannot accidentally corrupt data by using the mutating methods
unexpectedly.
If, for some reason, users of monotorrent need a mutable bitfield
then that can be exposed. However a better choice may be for them
to use the built in System.Collections.BitArray class.

[core] Make the 'BitField' mutating methods internal

---

src/MonoTorrent.Tests/Client/StreamingPieceRequesterTests.cs
src/MonoTorrent/MonoTorrent.Client.PiecePicking/StreamingPieceRequester.cs

A prior change to ensure pieces from within the high, or low
priority range were always prioritised ahead of pieces from
the 'not important at all' range accidentally made the picker
not chooose pieces from the 'not important at all' set.
This would have little significance for real world streaming
scenarios as the 'not important at all' set are pieces which
come are before the current file position, i.e. pieces the
media player would not try to use.
Fixes https://github.com/alanmcgovern/monotorrent/issues/425

Request any piece

---

src/MonoTorrent.Tests/Client/FastResumeTests.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent/MonoTorrent.Client/Modes/DownloadMode.cs
src/MonoTorrent/MonoTorrent.Client/Settings/EngineSettings.cs
src/MonoTorrent/MonoTorrent.Client/Settings/EngineSettingsBuilder.cs
src/MonoTorrent/MonoTorrent.Client/Settings/FastResumeMode.cs

Add the ability to store fast resume on a 'best effort' basis. When `FastResumeMode.BestEffort` is enabled, the engine will automatically save fast data on a regular cadence. This eliminates the need to completely rehash data, but it also means that if there is a crash any pieces which were downloaded in the meantime will be 'lost'. In practice this should be under 30 seconds worth of data.
If accuracy is needed, to reduce the need to re-download *any* data, `FastResumeMode.Accurate` can be used. This mode will cause fast-resume data to be deleted from the cache directory while the torrent is actively downloading, and fast resume data will only be written to disk when the manager enters a mode which *does not* modify data. i..e when the engine enters the `Stopped` mode or `Seeding` mode. …

Fast resume improvements

---

src/MonoTorrent/MonoTorrent.Client/ClientEngine.cs
src/MonoTorrent/MonoTorrent.Client/Settings/EngineSettings.cs
src/MonoTorrent/MonoTorrent.Client/Settings/EngineSettingsBuilder.cs

Don't default to using the current directory as the
cache directory. Instead throw an error if a value isn't
set by the user of the library.

[core] Force developers to set a usable cache directory

---

.gitignore
src/MonoTorrent/MonoTorrent.Client/ClientEngine.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent/MonoTorrent.Client/RemoveMode.cs

A few small tweaks here:
- Torrent metadata is always copied to the cache directory when a TorrentManager is loaded.
- The path to the torrent metadata is exposed via `TorrentManager.MetadataPath`.
- `ClientEngine.RemoveAsync` has an additional set of overloads which control how data is deleted when a torrent is removed from the engine. The default is to retain all downloaded data and clear anything in the cache directory.

Improve cache handling

---

src/MonoTorrent.Tests/Client/EngineSettingsTests.cs
src/MonoTorrent.Tests/Client/TorrentSettingsTests.cs
src/MonoTorrent/MonoTorrent.Client/Settings/EngineSettings.cs
src/MonoTorrent/MonoTorrent.Client/Settings/EngineSettingsBuilder.cs
src/MonoTorrent/MonoTorrent.Client/Settings/Serializer.cs
src/MonoTorrent/MonoTorrent.Client/Settings/TorrentSettings.cs

This can be refactored into a separate class. However the logic
should be nicely forwards/backwards compatible between versions.
Any missing settings will have their default value, and any
unknown settings will be ignored.

[core] Add serialization methods to [Torrent|Engine]Settings

---

src/MonoTorrent.Tests/Client/ClientEngineTests.cs
src/MonoTorrent/MonoTorrent.Client/ClientEngine.cs
src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent/MonoTorrent.Client/Settings/Serializer.cs
src/MonoTorrent/MonoTorrent/Torrent.cs

Save all user settable state, and allow reloading it later.
This will save the engine settings, the list of loaded
torrents, the settings for those, etc.

[core] Add a way to save/restore an entire ClientEngine

---

src/MonoTorrent.Connections/MonoTorrent.Connections/SocketPeerConnection.cs

This appears to work fine under UWP, .NET 4.7.2 and .NET Core 3.0+
Improves perf slightly, and also reduces memory allocations by a
large chunk.

[core] Suppress ExecutionContext flow for socket operations

---

src/MonoTorrent.Client/MonoTorrent/Torrent.cs
src/MonoTorrent.Client/MonoTorrent/TorrentFile.cs
src/Tests/Tests.MonoTorrent.Client/Common/TorrentV2Test.cs

Disable parsing of v2 only torrents by default so I can
incrementally add support throughout the library without
having to land one large pull request.

[bep52] Add parser support for the new style file dict

---

src/MonoTorrent.Client/MonoTorrent.Dht/NullDhtEngine.cs
src/MonoTorrent.Dht/MonoTorrent.Dht/DhtEngine.cs
src/MonoTorrent.Dht/MonoTorrent.Dht/MessageLoop.cs
src/MonoTorrent/MonoTorrent.Dht/IDhtEngine.cs
src/MonoTorrent/MonoTorrent/SpeedMonitor.cs
src/Tests/Tests.MonoTorrent.Client/Client/ManualDhtEngine.cs
src/Tests/Tests.MonoTorrent/SpeedMonitorTest.cs

Record total bytes sent/received, as well as the estimated transfer rate in bytes/second.

[dht] Use SpeedMonitor to calculate DHT data rates

---

src/Benchmark/Benchmark.csproj
src/Benchmark/Program.cs
src/MonoTorrent.PiecePicking/MonoTorrent.PiecePicking/StandardPicker.cs
src/Tests/Tests.MonoTorrent.PiecePicking/RandomisedPickerTests.cs

The delta between the first commit where the benchmark was added and the final performance improving commit is (currently):
Unoptimised code:
|                                     Method |     Mean |     Error |    StdDev | Allocated |
|------------------------------------------- |---------:|----------:|----------:|----------:|
|                            PickAndValidate | 8.229 ms | 0.0331 ms | 0.0310 ms |     16 KB |
|              PickAndValidate_600Concurrent | 7.451 ms | 0.0507 ms | 0.0475 ms |     16 KB |
| PickAndValidate_600Concurrent_60Requesters | 7.361 ms | 0.0313 ms | 0.0293 ms |     16 KB |
Optimised code:
|                                     Method |     Mean |   Error |  StdDev |  Gen 0 | Allocated |
|------------------------------------------- …

Piece picking perf improvements

---

src/MonoTorrent.Client/MonoTorrent.Client/FastResume/FastResume.cs
src/Tests/Tests.MonoTorrent.Client/Client/FastResumeTests.cs

Since `FastResume.Encode()` can write to a stream, it makes sense to allow `FastResume.TryLoad()` to read from a stream. This allows a client application to manage collections of `FastResume` objects.
Right now there is no other way because all constructors are internal.

[core] Allow to load FastResume objects from a stream

---

src/MonoTorrent.Client/MonoTorrent.Client/ClientEngine.cs

Now it's threadsafe when users call StartAsync/StopAsync on multiple different `TorrentManager` instances concurrently.
Fixes https://github.com/alanmcgovern/monotorrent/issues/499

[core] Ensure the dht node cahe is written safely

---

src/MonoTorrent.Client/MonoTorrent/Torrent.cs
src/MonoTorrent/MonoTorrent/Constants.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent/TorrentV2Test.cs
src/Tests/Tests.MonoTorrent.Client/Tests.MonoTorrent.Client.csproj

This validates the piece data isn't corrupt/faked in the torrent.

[bep52] Validate 'piece layers' when loading BEP52 torrents

---

src/MonoTorrent.Client/MonoTorrent.Client.Modes/HashingMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/Mode.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent.Client/MonoTorrent/PieceHashes.cs
src/MonoTorrent.Client/MonoTorrent/PieceHashesV2.cs
src/MonoTorrent.Client/MonoTorrent/Torrent.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.Modes/HashingModeTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent/TorrentV2Test.cs

The torrent metadata is no longer the source of truth for piece
hashes. Piece hashes are optionally part of a bittorrent v2 (bep52)
compliant torrent. In the event they're missing, they can be requested
from peers after the metadata has been retrieved.
One invariant I wish to maintain is that the 'Torrent' object should be
completely immutable.
As such, remove the 'IPieceHashes PieceHashes' property and
expose a public method instead. This method has an overload where you
can supply a Dictionary of piece hashes, keyed by
'ITorrentFile.PiecesRoot'. This way an IPieceHashes object can be
created after hashes are fetched from another peer and those hashes
have been validated as being correct.
'TorrentManager' is mutable and stores the latest version of the
PieceHashes object, allowing it to …

[bep52] Modify the API to support dynamically retrieving Bep52 hashes

---

src/MonoTorrent.Client/MonoTorrent.Client/Managers/PieceManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent.Client/MonoTorrent/IPieceHashes.cs
src/MonoTorrent.Client/MonoTorrent/PieceHashesV1.cs
src/MonoTorrent.Client/MonoTorrent/PieceHashesV2.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent/PieceHashesTests.cs

The addition of this bitfield ensures no pieces are downloaded by the
engine until V2 piece hashes have been fetched. For V1 only torrents
this will have no effect.

[bep52] Ensure nothing is downloaded before piece hashes are available

---

src/MonoTorrent.Client/MonoTorrent.Client.Modes/PieceHashesMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/StartingMode.cs
src/MonoTorrent.Client/MonoTorrent/Enums.cs

There's some cleanup for this PR already, but the gist of it is.
1) The torrent metadata is no longer the source of truth for piece
hashes. As such, remove the 'IPieceHashes PieceHashes' property and
expose a public method instead. This method has an overload where you
can supply a Dictionary of piece hashes, keyed by
'ITorrentFile.PiecesRoot'. This way an IPieceHashes object can be
created after hashes are fetched from another peer *and* those hashes
have been validated as being correct. This cleanup should be on PR.
2) Add another 'ignorable bitfield' which will be used to represent
missing hashes. If we do not have the hashes for a particular piece,
the corresponding bit in that bitfield will be set to true so it will
never be requested. This needs to be plumbed through properly and …

Add the beginnings of a 'FetchHashes' mode.

---

src/MonoTorrent.Client/MonoTorrent.Client.Modes/Mode.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/EngineSettings.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/EngineSettingsBuilder.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/TorrentSettings.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/TorrentSettingsBuilder.cs
src/MonoTorrent.Client/MonoTorrent.Connections/HttpPeerConnection.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/TestWebSeed.cs

Increase some timeouts as some web servers, specifically some
from internet archive, take longer than 10 seconds to respond,
which means the time between block requests can be significantly
longer than 15 seconds too.
These new (arbitrary) values are enough to reliably download from
both webseed urls for the public domain torrent listed in
https://github.com/alanmcgovern/monotorrent/issues/538

[webseed] This should be moved to engine level config

---

src/MonoTorrent.Client/MonoTorrent.Client/Managers/DiskManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/EngineSettings.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/EngineSettingsBuilder.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/Serializer.cs
src/MonoTorrent.Factories/MonoTorrent/Factories.cs
src/MonoTorrent.PieceWriter/MonoTorrent.PieceWriter/MemoryCache.cs
src/MonoTorrent/MonoTorrent.PieceWriter/CachePolicy.cs
src/MonoTorrent/MonoTorrent.PieceWriter/IBlockCache.cs
src/Tests/Tests.MonoTorrent.PieceWriter/MemoryCacheTests.cs

This will be useful when creating torrents. In this scenario
we want to be able to read a piece into memory, hash it using
both SHA1 and SHA256, and then return the bittorrent v1 and
v2 hashes for that piece.
Afterwards, we need to compute the SHA1 and MD5 hashes for the
individual file. This would normally require re-reading the
exact same data from disk, but now we can fetch it from memory.

[piecewriter] Add a cache policy so reads can be cached

---

src/MonoTorrent.Client/MonoTorrent.Client.Modes/PieceHashesMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/StartingMode.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/DiskManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentFileInfo.cs
src/MonoTorrent.Client/MonoTorrent/EditableTorrent.cs
src/MonoTorrent.Client/MonoTorrent/MerkleLayers.cs
src/MonoTorrent.Client/MonoTorrent/PieceHashesV2.cs
src/MonoTorrent.Client/MonoTorrent/ReadOnlyMerkleLayers.cs
src/MonoTorrent.Client/MonoTorrent/Torrent.cs
src/MonoTorrent.Client/MonoTorrent/TorrentCreator.cs
src/MonoTorrent.Client/MonoTorrent/TorrentFile.cs
src/MonoTorrent.Client/MonoTorrent/TorrentFileSource.cs
src/MonoTorrent.Client/MonoTorrent/TorrentType.cs
src/MonoTorrent.Messages/MonoTorrent.Messages.Peer/HashRejectMessage.cs
src/MonoTorrent.Messages/MonoTorrent.Messages.Peer/HashRequestMessage.cs
src/MonoTorrent.Messages/MonoTorrent.Messages.Peer/HashesMessage.cs
src/MonoTorrent.PieceWriter/MonoTorrent.PieceWriter/IPieceWriterExtensions.cs
src/MonoTorrent/MonoTorrent.PieceWriter/IPieceWriter.cs
src/MonoTorrent/MonoTorrent/ITorrentInfo.cs
src/MonoTorrent/MonoTorrent/MerkleRoot.cs
src/Samples/SampleClient/StressTest.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.Modes/PieceHashesModeTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/TestRig.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent/MerkleTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent/TorrentCreatorBep47Tests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent/TorrentCreatorTests.cs
src/Tests/Tests.MonoTorrent.Messages/StandardMessageTests.cs

Augment `TorrentCreator` to allow creating different kinds of torrents. By default `TorrentCreator` will now create hybrid torrents, with V1 and V2 metadata.
A `TorrentType` parameter can be passed to the `TorrentCreator` to allow creating a torrent file with:
- BitTorrent V1 metadata
- BitTorrent V1 metadata with [BEP47 ](https://www.bittorrent.org/beps/bep_0047.html) compliant padding/alignment. All files align with the start of a piece.
- A [BEP 52 ](https://www.bittorrent.org/beps/bep_0052.html) compliant hybrid V1/V2 torrent, contains BitTorrent V1 and BitTorrentV2 metadata.
- A [BEP 52](https://www.bittorrent.org/beps/bep_0052.html) compliant V2 torrent, does not contain BitTorrent V1 metadata.

Add support for creating V1/V2 hybrid  torrents, and V2 torrents

---

src/MonoTorrent.Client/MonoTorrent.Client/Managers/DiskManager.cs
src/MonoTorrent.Client/MonoTorrent/TorrentCreator.cs
src/MonoTorrent.PieceWriter/MonoTorrent.PieceWriter/FileStreamBuffer.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent/TorrentCreatorBep47Tests.cs

Use some fancier threading here to ensure disk IO happens in
parallel with hashing data. This allows the creator to create a
V1/V2 hybrid torrent with a 2.6GB input file in approximately
6.2 seconds seconds instead of 9-12 seconds.

[core] Optimise TorrentCreator performance

---

src/MonoTorrent.Dht/MonoTorrent.Dht/DhtEngine.cs
src/Tests/Tests.MonoTorrent.Dht/MonoTorrent.Dht/DhtEngineTests.cs
src/Tests/Tests.MonoTorrent.Dht/MonoTorrent.Dht/MessageHandlingTests.cs

Handle adding nodes to the engine before calling StartAsync. These should be cached and then checked whenever `StartAsync` is invoked

[dht] Fix a DHT initialization issue

---

src/MonoTorrent.Client/MonoTorrent.Client.Modes/PieceHashesMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/StartingMode.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/ConnectionManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/MessageQueue.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/EngineSettings.cs
src/MonoTorrent.Client/MonoTorrent/ReadOnlyMerkleLayers.cs

If a V2 (or hybrid) magnet link is used and the v2 hashes are missing,
then we will fetch them from other peers on the swarm. Once they are
received, cache them alongside any cached metadata so they can be
implicitly reloaded the next time the torrent is started.

[core] Cache bittorrent v2 hashes after retrieving them

---

src/MonoTorrent.Client/MonoTorrent.Client/Settings/EngineSettings.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/EngineSettingsBuilder.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/Serializer.cs
src/MonoTorrent.Client/MonoTorrent.Streaming/HttpStream.cs
src/MonoTorrent.Client/MonoTorrent.Streaming/StreamProvider.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/EngineSettingsTests.cs

THe library can now be configured to use any ip or port when
setting up the HttpListener to serve data when a torrent is
set up to support streaming.

[core] Make the Http streaming uri configurable

---

src/MonoTorrent.Client/MonoTorrent/Torrent.cs
src/MonoTorrent.Client/MonoTorrent/TorrentCreator.cs
src/MonoTorrent.Client/MonoTorrent/TorrentFile.cs
src/MonoTorrent/MonoTorrent/ITorrentInfo.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent/TorrentCreatorTests.cs

Zero length files should not have a root hash as they have no data. Skip them!
Fixes https://github.com/alanmcgovern/monotorrent/issues/560

[bep52] Fix creating v2 torrents with zero length files

---

src/MonoTorrent.Client/MonoTorrent/TorrentCreator.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent/TorrentCreatorTests.cs

As the underlying storage is a bencoded dictionary, whose keys must be sorted, you *must* sort the list of files which will be placed in a hybrid or v2 torrent prior to hashing them, otherwise the order of the files will be flipped and piece hashes won't match anymore.
This doesn't appear to be mentioned in the spec, but is called out in a code comment in the sample torrent creator linked as part of the bep52 spec.
I went hunting as soon as i realised i didn't know how to make this test pass as the files were not in a bencoded list.
Fixes https://github.com/alanmcgovern/monotorrent/issues/563
Test case written by @borigas

[core] Sort files before creating hybrid or v2 torrents

---

src/MonoTorrent.Client/MonoTorrent.Client.Modes/MetadataMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/Mode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/PieceHashesMode.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/ConnectionManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/PieceManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentManager.cs

This change ensures that requests for pieces, metadata or bittorrent v2 hashes use a consistent mechanism for timing out when peers fail to send the requested data. When a timeout occurs, the connection to the peer is closed, all pending requests are cancelled and the data will be re-requested from a new peer.
Fixes https://github.com/alanmcgovern/monotorrent/issues/559

Handle timeouts requesting metadata

---

src/MonoTorrent.Client/MonoTorrent.Client/Managers/TrackerManager.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/TestRig.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/TrackerManagerTests.cs

This should prevent unbounded memory usage by ensuring all 'periodic' announces fast-path and exit if there is an in-progress announce.
Non-periodic announces are enqueued, and execute
sequentially.
When an announce is executing, up to 10 tracker tiers will be announced to concurrently.
Fixes:
https://github.com/alanmcgovern/monotorrent/issues/571 https://github.com/alanmcgovern/monotorrent/issues/450

[core] Refactor how announce requests are handled.

---

src/Tests/Tests.MonoTorrent.IntegrationTests/IntegrationTests.cs

Maybe there's a bug in the finalizer chain and it's causing this crash during app shutdown:
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.ObjectDisposedException: Safe handle has been closed. Object name: 'SafeHandle'.
at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
at Interop.HttpApi.HttpCancelHttpRequest(SafeHandle requestQueueHandle, UInt64 requestId, IntPtr pOverlapped)
at System.Net.HttpListenerContext.ForceCancelRequest(SafeHandle requestQueueHandle, UInt64 requestId)
at System.Net.HttpListenerContext.Abort()
at System.Net.HttpResponseStream.EndWriteCore(IAsyncResult asyncResult)
at …

[tests] Stop the HttpListener as part of teardown

---

src/MonoTorrent.Client/MonoTorrent.Client.Modes/ErrorMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/HashingMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/IMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/MetadataMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/Mode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/PieceHashesMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/StartingMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/StoppedMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/StoppingMode.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentManager.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.Modes/HashingModeTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.Modes/StartingModeTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.Modes/StoppedModeTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.Modes/StoppingModeTests.cs

Refactor Mode/IMode to make it clearer what logic is being executed as part of each mode. As part of this ensure that announcing and peer maintenance is handled the same way for DownloadMode, MetadataMode and PieceHashesMode.
Addresses https://github.com/alanmcgovern/monotorrent/issues/447

Fixup modes

---

src/MonoTorrent.Client/MonoTorrent.Client.Modes/Mode.cs

From EngineSettingsBuilder.cs
```
/// <summary>
/// The download speed under which a torrent will start using web seeds. A value of
/// 0 means webseeds will be added regardless of how fast the torrent is downloading.
/// </summary>
public int WebSeedSpeedTrigger {
```

Start web seed if the speed trigger is 0

---

src/MonoTorrent.BEncoding/MonoTorrent.BEncoding.csproj
src/MonoTorrent.Client/MonoTorrent.Client.csproj
src/MonoTorrent/MonoTorrent.csproj
src/Samples/Directory.Build.props

This should explicitly reference System.Memory, fixing the issue experienced here: https://github.com/alanmcgovern/monotorrent/issues/581

[core] Properly specify the System.Memory reference

---

src/MonoTorrent.Client/MonoTorrent/Torrent.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent/TorrentTest.cs

Let me know if you'd like a more descriptive commit message, or if I should add a description like I did in #583.

[core] Skip parsing key if value is an empty string

---

src/MonoTorrent.Client/MonoTorrent.Client.Modes/Mode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Tracker/TrackerRequestFactory.cs
src/MonoTorrent.Client/MonoTorrent.Client/ClientEngine.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/ListenManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/EngineSettings.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/EngineSettingsBuilder.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/Serializer.cs
src/MonoTorrent.Connections/MonoTorrent.Connections.Peer/SocketPeerConnection.cs
src/Samples/SampleClient/StandardDownloader.cs
src/Samples/SampleClient/StressTest.cs
src/Samples/SampleClient/main.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/EngineSettingsTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/TestRig.cs
src/Tests/Tests.MonoTorrent.IntegrationTests/IntegrationTests.cs

Default to creating an IPV4 and IPV6 listener, bound to IPAddress.Any/IPV6Any, and port 0. Additionally, allow configuring an alternative reported IP address for both IPV4 and IPV6.
Partially fixes https://github.com/alanmcgovern/monotorrent/issues/588

[IPV6] Support setting multiple listeners and reported endpoints

---

src/MonoTorrent.Client/MonoTorrent.Client.Modes/Mode.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/PeerExchangeManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Peers/Peer.cs
src/MonoTorrent.Client/MonoTorrent.Client/Peers/PeerDecoder.cs
src/MonoTorrent.Dht/MonoTorrent.Dht.Tasks/GetPeersTask.cs
src/MonoTorrent.Dht/MonoTorrent.Dht/DhtEngine.cs
src/MonoTorrent.Trackers/MonoTorrent.Client.Messages.UdpTracker/AnnounceResponseMessage.cs
src/MonoTorrent.Trackers/MonoTorrent.Client.Messages.UdpTracker/UdpTrackerMessage.cs
src/MonoTorrent.Trackers/MonoTorrent.Connections.Tracker/HTTPTrackerConnection.cs
src/MonoTorrent.Trackers/MonoTorrent.Connections.Tracker/UdpTrackerConnection.cs
src/MonoTorrent.Trackers/MonoTorrent.Connections.TrackerServer/UdpTrackerListener.cs
src/MonoTorrent/MonoTorrent.Connections.Peer/IPeerConnection.cs
src/MonoTorrent/MonoTorrent.csproj
src/MonoTorrent/MonoTorrent/PeerInfo.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/PeerInfoTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/UdpTrackerTests.cs

Augment `PeerInfo` to also support parsing IPV6 addresses. The format used to parse the compact peer notation into an actual IPAddress/Uri is still hardcoded to assume IPV4 in a few places, though that's primarily because more groundwork needs to be done to fully map IPv6 throughout dht, peer exchange, etc.
Some parts of the spec are written to allow sending `ipv4` and `ipv6` formats in the same message, others use the active connection type to discriminate. i.e. if you send a udp request over ipv4 you get ipv4 peers back, if you send it over ipv6 you get ipv6 peers.
It makes it a bit more complicated to support as a result.
https://github.com/alanmcgovern/monotorrent/issues/588

[core] Support ipv4 and ipv6 compact addresses

---

src/MonoTorrent.PieceWriter/MonoTorrent.PieceWriter/DiskWriter.cs
src/Tests/Tests.MonoTorrent.PieceWriter/DiskWriterTests.cs

This regressed as the code which used to validate this was refactored/rewritten when creating IBlockCache.
Fixes https://github.com/alanmcgovern/monotorrent/issues/595
Thanks to @ManlyMarco for reporting.

[PieceWriter] Add a test covering 'unlimited' open files

---

src/MonoTorrent.Client/MonoTorrent.Client.Modes/DownloadMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/ErrorMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/HashingMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/IMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/Mode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/PausedMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/StartingMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/StoppedMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/StoppingMode.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentManager.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.Modes/DownloadModeTests.cs

There are several cases where the 'AmInterested' status can change for a given peer, and it's not easy to provide an event for each of these.
For example, the 'interested' status is dependent on each bitfield added as an 'IgnoringBitfield' to the piecepicker. These bitfields can change arbitrarily. This async check will ensure that things will refresh regularly.
As updating the priority of a file does have a pretty clear user action associated with it, special case this to cause an immediate refresh of the 'AmInterested' status.
Fixes https://github.com/alanmcgovern/monotorrent/issues/597

[core] Refresh the 'AmInterested' status regularly

---

src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent.PieceWriter/MonoTorrent.PieceWriter/DiskWriter.cs
src/Tests/Tests.MonoTorrent.IntegrationTests/IntegrationTests.cs

The support to move files while the torrent is actively running was added as part of https://github.com/alanmcgovern/monotorrent/pull/445 .
Remove the code which prevents users from being able to do this.
Partially fixes: https://github.com/alanmcgovern/monotorrent/issues/598

[core] Allow moving files at any point

---

src/MonoTorrent.Client/MonoTorrent.Client/ClientEngine.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/DiskManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentFileInfo.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent.PieceWriter/MonoTorrent.PieceWriter/DiskWriter.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/ClientEngineTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/DiskManagerExceptionTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/DiskManagerTests.cs

This adds several additional tests covering aspects of how this feature was intended to operate.
The 'Complete' and 'Incomplete' paths are now generated using a helper method. The choice of whether or not to use the 'Complete' or 'Incomplete' path as the current path is dependent on whether or not 'UsePartialFiles' is on, and if the file is already considered 'complete' or 'incomplete'.
This should keep everything in sync when toggling UsePartialFiles on and off, and also if the user uses 'MoveFileAsync', or 'MoveFilesASync' to move files.
The code docs should also be updated to clarify that if `UsePartialFiles` is enabled and someone moves an incomplete file to `some_directory/file.ext` then the engine will actually move the file to `some_directory/file.ext.!mt` as it is a *partial* …

[core] Fix several bugs with 'EngineSettings.UsePartialFiles'

---

src/MonoTorrent.Client/MonoTorrent/TorrentCreator.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent/TorrentCreatorBep47Tests.cs

When sorting files for BEP52 compatibility, use an ordinal comparison rather than the default culture aware comparison.
BitTorrent relies on ordinal comparisons when sorting keys inside BEncodedDictionaries, and that is the order which must be respected here.
Fixes a regression from https://github.com/alanmcgovern/monotorrent/commit/3d3937dbdfe44a81923db9d04c25c9c6a1ee0296
Fixes https://github.com/alanmcgovern/monotorrent/issues/610

[core] Fix a BEP52 related regression

---

src/MonoTorrent.Client/MonoTorrent/Torrent.cs
src/MonoTorrent.Client/MonoTorrent/TorrentCreator.cs
src/MonoTorrent.Client/MonoTorrent/TorrentFile.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent/TorrentCreatorBep47Tests.cs

When torrents contain multiple sequential empty files, ensure padding data is applied to the closest non-empty file, rather than simply the closest file.

[bep52|bep47] Fix file ordering sanity check and padding for empty files

---

src/MonoTorrent.Client/MonoTorrent.Client.RateLimiters/RateLimiter.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.RateLimiters/RateLimiterTests.cs

If the ratelimiter is set to download at 15kB/sec or less, the amount of data in the ratelimit will always be less than the size of one block. In this case, we should allow the request to succeed.
Once there's negative data left in the allowance, deny requests. As the ratelimiter is topped up over time, future requests will be unblocked.

[core] Ratelimiters should allow requests larger than chunk size

---

src/MonoTorrent.Client/MonoTorrent.Client/Peers/PeerDecoder.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/PeerInfoTests.cs

When decoding a tracker response which contains non-compact data, ensure IPv6 peers are parsed with the 'ipv6' prefix.
Additionally, this data is now validated to ensure it's a valid IP address and port.

[ipv6] Use the correct prefix for IPv6 non-compact peers

---

src/MonoTorrent.Client/MonoTorrent.Client.RateLimiters/IRateLimiter.cs
src/MonoTorrent.Client/MonoTorrent.Client.RateLimiters/RateLimiter.cs
src/MonoTorrent.Client/MonoTorrent.Client.RateLimiters/RateLimiterGroup.cs
src/MonoTorrent.Client/MonoTorrent.Client/ClientEngine.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/DiskManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/NetworkIO.cs
src/MonoTorrent.Client/MonoTorrent.TrackerServer/SimpleTorrentManager.cs
src/MonoTorrent.Client/MonoTorrent.TrackerServer/TrackerServer.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.RateLimiters/RateLimiterTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/DiskManagerTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/NetworkIOTests.cs

Fix another issue with a ratelimit of 1 byte/second. Hopefully no-one was actually trying to use a limit this low.
Additionally, simplify this logic now. Rate limits are much easier than they used to be as the engine works in bytes, not 'blocks' or 'chunks'.
Back in the day there had to be estimates made for the amount of data which would be received for a given 'ReceiveAsync' call. Now we're just counting the raw number of bytes sent/received, or read/written, so we don't need complicated math to account for over/under-shoot.

[core] Tweak ratelimiting a little better for low rates

---

src/MonoTorrent.Client/MonoTorrent.Client.Listeners/NullPeerListener.cs
src/MonoTorrent.Client/MonoTorrent.Client/ClientEngine.cs
src/MonoTorrent.Connections/MonoTorrent.Connections.Peer/LocalPeerDiscovery.cs
src/MonoTorrent.Connections/MonoTorrent.Connections.Peer/PeerConnectionListener.cs
src/MonoTorrent.Connections/MonoTorrent.Connections/SocketListener.cs
src/MonoTorrent.Connections/MonoTorrent.Connections/UdpListener.cs
src/MonoTorrent/MonoTorrent.Connections.Peer/IPeerConnectionListener.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/ClientEngineTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/TestRig.cs

The main part of this change is that the actual IPEndPoint which the listnener has been bound to is not the sole source of the 'port' value which should be sent to the tracker.
If the listener has been configured to bind to a specific port, but has (at the point in time when the announce is sent) not successfully bound to that port, the preferred port should be sent to the tracker.
If the user has configured the listener to port '0' *and* the listener isn't running, then we have a problem as 'port' is a required parameter and must be sent. In this scenario, send an invalid port and the tracker should still return a list of peers to connect to.
Fixes 1/2 of https://github.com/alanmcgovern/monotorrent/issues/613

[core] Try harder to send a valid port to the tracker

---

src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentManager.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/ClientEngineTests.cs

Now this can be invoked while the torrent is active.

[core] Remove the restriction on 'MoveFileAsync'

---

src/MonoTorrent.Client/MonoTorrent.Client.Listeners/NullPeerListener.cs
src/MonoTorrent.Client/MonoTorrent.Client/ClientEngine.cs
src/MonoTorrent.Connections/MonoTorrent.Connections.Peer/LocalPeerDiscovery.cs
src/MonoTorrent.Connections/MonoTorrent.Connections.Peer/PeerConnectionListener.cs
src/MonoTorrent.Connections/MonoTorrent.Connections/SocketListener.cs
src/MonoTorrent.Connections/MonoTorrent.Connections/UdpListener.cs
src/MonoTorrent/MonoTorrent.Connections.Peer/IPeerConnectionListener.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/ClientEngineTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/TestRig.cs

If a client sends an invalid port, we can still send peers to them.
Fixes 1/2 of https://github.com/alanmcgovern/monotorrent/issues/613

[server] Properly handle invalid port values

---

src/MonoTorrent.Client/MonoTorrent.Client.Modes/Mode.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/TorrentSettings.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/TorrentSettingsBuilder.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.Modes/DownloadModeTests.cs

If a connection has already been made to a particular ip/port and the peer_id is known, or if a non-compact response is returned by the tracker so the peer_id for a given remote ip/port is 'known', do *not* close the connection if the actual client at that ip/port returns a different peer_id.
While the torrent spec requires that these connections be closed, there are a few reasons which make this fairly pointless.
1) libtorrent randomises these by default. Other clients probably randomise these too.
2) It's normal for these to change when a client restarts anyway. Clients may be restarted for any number of reasons.
3) They're not transmitted by DHT, and are not transmitted by the tracker by default.
4) The onus is on the *connecting* peer to close the connection, which means the check is …

[core] Don't require peer_ids to match expectations

---

src/MonoTorrent/MonoTorrent/InfoHash.cs

UriHelper uses outdated standard and makes hashes which sometimes are not accepted by trackers, for example if infohash contains 0x20 (space) it's substituted with '+' sign.

Backported use of UrlEncode/UrlDecode from HttpUtility in Infohash

---

README.md

The old link sometimes shows "An Internal error occurred" error, maybe there's a problem with Open Collective redirections?
Very small change.

Fixing "Contribute" links.

---

azure-pipelines.yml

If HttpListener throws an exception in it's async callback because it's already been disposed, then it's a framework bug and they should fix it. I'm pretty sure i filed it before and it wasn't addressed, so work around it by ignoring the exit code from the test running process and only fail the build if tests have failed.
This is no longer causing red builds:
```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
at Interop.HttpApi.HttpCancelHttpRequest(SafeHandle requestQueueHandle, UInt64 …
```

Work around a HttpListener framework bug

---

src/Logger.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/Mode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/PieceHashesMode.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentFileInfo.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/EngineSettings.cs
src/MonoTorrent.Client/MonoTorrent/IPieceHashes.cs
src/MonoTorrent.Client/MonoTorrent/MerkleHash.cs
src/MonoTorrent.Client/MonoTorrent/MerkleLayers.cs
src/MonoTorrent.Client/MonoTorrent/PieceHashes.cs
src/MonoTorrent.Client/MonoTorrent/PieceHashesV1.cs
src/MonoTorrent.Client/MonoTorrent/PieceHashesV2.cs
src/MonoTorrent.Client/MonoTorrent/ReadOnlyMerkleLayers.cs
src/MonoTorrent.Client/MonoTorrent/Torrent.cs
src/MonoTorrent.Client/MonoTorrent/TorrentFile.cs
src/MonoTorrent.Messages/MonoTorrent.Messages.Peer/HashRejectMessage.cs
src/MonoTorrent.Messages/MonoTorrent.Messages.Peer/HashRequestMessage.cs
src/MonoTorrent.Messages/MonoTorrent.Messages.Peer/HashesMessage.cs
src/MonoTorrent.Messages/MonoTorrent.Messages.csproj
src/MonoTorrent.PieceWriter/MonoTorrent.PieceWriter/RandomFileStream.cs
src/MonoTorrent/MonoTorrent/ITorrentFile.cs
src/MonoTorrent/MonoTorrent/ITorrentInfo.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.Modes/PieceHashesModeTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent/MerkleLayersTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent/MerkleTests.cs
src/Tests/Tests.MonoTorrent.IntegrationTests/IntegrationTests_RealPieceWriter.cs
src/Tests/TorrentInfoHelpers.cs

Fixed several bugs around requesting piece hashes for BEP52 torrents. Such as:
* Correct handling for requesting piece hashes when the piece layer is not an exact power of 2 in length.
* Correct handling of torrents which consist of files small enough to fit inside 1 piece.
* Correct handling of torrents containing duplicate files (which have the same underlying hash!)
* Improved logging for debugging purposes

MetadataMode - bep52

---

src/Directory.Build.props

This greatly simplifies debugging.
These days storage is cheap, and debug symbols are small.
Removes the need to upload debug symbols separately, setting up debuggers to download them from NuGet (or you name it), etc etc etc

Embed debug info into DLLs

---

src/MonoTorrent.Client/MonoTorrent.Connections/HttpPeerConnection.cs
src/MonoTorrent.PiecePicking/MonoTorrent.PiecePicking/StandardPieceRequester.cs
src/MonoTorrent.PiecePicking/MonoTorrent.PiecePicking/StreamingPieceRequester.cs
src/Tests/Tests.MonoTorrent.IntegrationTests/IntegrationTests_FakePieceWriter.cs
src/Tests/Tests.MonoTorrent.IntegrationTests/IntegrationTests_RealPieceWriter.cs
src/Tests/Tests.MonoTorrent.IntegrationTests/Tests.MonoTorrent.IntegrationTests.csproj
src/Tests/Tests.MonoTorrent.PiecePicking/StandardPieceRequesterTests.cs

1) Ensure web requests request data in-order by fixing the piecepicker
to correctly use 'CanRequestMorePieces'
2) Fix a bug in the handling of padding files. A request for some data
from a webseed needs to take padding files into account in all cases.
A request can begin or end inside padding, it can also begin/end in
regular files while optionally crossing one stretch of padding. This
means the existing logic to insert synethic requests to the padding
file are broken in a number of cases.

Fix two issues affecting webseeds

---

src/MonoTorrent.Client/MonoTorrent.Connections/HttpPeerConnection.cs

Tweak of the https://github.com/alanmcgovern/monotorrent/pull/639 PR - except raise an exception instead!

Add validation http requests

---

src/MonoTorrent.Dht/MonoTorrent.Dht.Tasks/InitialiseTask.cs
src/MonoTorrent.Dht/MonoTorrent.Dht/DhtEngine.cs
src/Samples/DhtSampleClient/Program.cs

Add support for transmissions router (in the event the others are offline) while also add a public API so custom routers can be supplied when initialising a DhtEngine directly.

[dht] Allow bootstrapping from additional bootstrap routers

---

src/MonoTorrent.Client/MonoTorrent.Client.Modes/PieceHashesMode.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/ConnectionManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/ListenManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentManager.cs
src/MonoTorrent.Messages/MonoTorrent.Messages.Peer/HandshakeMessage.cs
src/Tests/Tests.MonoTorrent.IntegrationTests/IntegrationTests_RealPieceWriter.cs

As per BEP52 - if a connection is initiated with the V1 infohash and the relevant reserved bit is set, respond with the V2 infohash to upgrade the connection to 'V2' mode. This makes it unambiguous as to whether or not a given peer supports BEP52.
More importantly, the 'ExpectedInfoHash' property is now the clear indicator as to whether a given peer supports BEP52 or not, as it will always be set to the V2 infohash *if* the peer supports V2 torrents.
This means peers supporting v1 only can be filtered out when requesting piecelayers from other V2 peers.

Disambiguate between v1 and v2 connections more clearly

---

src/MonoTorrent.Client/MonoTorrent.Client/ClientEngine.cs
src/MonoTorrent/MonoTorrent.Connections.Peer/IPeerConnectionListener.cs

This makes it easier for everyone to determine which specific local ports are bound when '0' is used as the preferred port.

Expose IPeerConnectionListeners publicly

---

src/MonoTorrent.Client/MonoTorrent.Client/ClientEngine.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/ListenManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentManager.cs
src/Tests/Tests.MonoTorrent.IntegrationTests/IntegrationTests_RealPieceWriter.cs

backfills tests for https://github.com/alanmcgovern/monotorrent/commit/89874d046e345046ed8922be702512aa120b6f55

Add tests for hash sharing

---

src/Logger.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/ListenManager.cs

I believe one of the integration tests is racing in CI as there's no explicit 'wait until ready' when starting the 'Leecher' download. As such, the seeder is nearly definitely initiating connections before the leecher is finished starting.

Add logging for incoming connections

---

src/MonoTorrent.Client/MonoTorrent/Torrent.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent/TorrentTest.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent/TorrentV2Test.cs

These were useful during initial implementation, but it's ok to remove them now. They'll always be on.

Remove the internal feature flags to disable BitTorrent V2 support

---

src/MonoTorrent.Client/MonoTorrent/Torrent.cs
src/MonoTorrent.Client/MonoTorrent/TorrentCreator.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent/TorrentCreatorBep47Tests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent/TorrentCreatorTests.cs

The test didn't verify the underlying bencoded dictionary contained no 'pieces root', but it did verify that no pieces root was loaded for zero length files.
This fixes one potential source of incompatibility when working with zero length files.

Improve the test which validates empty files in hybrid torrents (issue #685)

---

src/MonoTorrent.Client/MonoTorrent.Client/Managers/ConnectionManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/ListenManager.cs
src/MonoTorrent.Client/MonoTorrent.Connections.Peer.Encryption/EncryptorFactory.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.Modes/MetadataModeTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/ConnectionManagerTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/EncryptorFactoryTests.cs

We allow up to 'Timeout' seconds to establish a connection. We now also allow an additional 'Timeout' seconds for the handshake to complete before the connection is discarded.
A recent change made it so that peers who are in the handshaking phase are no longer counted as 'connected', so the timeout which disconnects peers who don't send messages within a reasonable amount of time doesn't apply, and prior to this commit the connection timeout only applied to the actual Socket.Connect.

Treat peers as 'connecting' until the handshake completes

---

src/MonoTorrent.Client/MonoTorrent.Client.Modes/DownloadMode.cs
src/MonoTorrent.Client/MonoTorrent.Client.Modes/Mode.cs
src/MonoTorrent.Client/MonoTorrent.Client/ConnectionFailureReason.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/ConnectionManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/ListenManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/PeerExchangeManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/PeerId.cs
src/MonoTorrent.Client/MonoTorrent.Client/Peers/Peer.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/EngineSettings.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/EngineSettingsBuilder.cs
src/MonoTorrent.Client/MonoTorrent.Client/Settings/Serializer.cs
src/Samples/SampleClient/StandardDownloader.cs
src/Samples/SampleClient/VLCStream.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.Modes/MetadataModeTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/ConnectionManagerTests.cs

The library will now try every supported encryption method each time it attempts to establish a connection, and it'll try to establish a connection a fixed number of times before bailing out. Each (overall) retry will be spaced out in time in case the receiving client is temporarily busy or inaccessible.

Restructure how peer connection retries are executed

---

src/MonoTorrent.Client/MonoTorrent.Client/ConnectionFailureReason.cs
src/MonoTorrent.Client/MonoTorrent.Client/EventArgs/AttemptConnectionEventArgs.cs
src/MonoTorrent.Client/MonoTorrent.Client/EventArgs/AttemptConnectionStage.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/ConnectionManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/ListenManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/PeerManager.cs

The current implementation only checks if a peer should be banned during `TryConnect`. This PR adds a check using `ShouldBanPeer()` within the `IncomingConnectionAcceptedAsync()` method to ensure that peers are also evaluated for banning when an incoming connection is accepted.
- Added `ShouldBanPeer()` check in `IncomingConnectionAcceptedAsync()`.
Enhancing the robustness of the peer banning mechanism by ensuring that peers are evaluated for banning not only during connection attempts but also when incoming connections are accepted.

Check and ban peer when accepting incoming connection

---

src/MonoTorrent.Client/MonoTorrent.Client.Modes/Mode.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/IPeerExchangeSource.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/PeerExchangeManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/PeerId.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/PeerExchangeManagerTests.cs

Rather than listening to the events, which are asynchronous, just call the PeerExchangeManager methods directly when a peer connects or disconnects. This ensures the methods are called on the main thread.
Probably fixes https://github.com/alanmcgovern/monotorrent/issues/695, where null reference exceptions are thrown when encoding peers in a peer exchange message.
One codepath/thread probably added/removed peers from the list and another thread did the same. This left things out of sync.

Handle PeerExchangeManager on the right thread

---

src/MonoTorrent.Client/MonoTorrent.Client.Modes/Mode.cs
src/MonoTorrent.Client/MonoTorrent.Client/ConnectionFailureReason.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/ConnectionManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/Managers/ListenManager.cs
src/MonoTorrent.Client/MonoTorrent.Client/PeerId.cs
src/MonoTorrent.Client/MonoTorrent.Client/Peers/Peer.cs
src/MonoTorrent.Client/MonoTorrent/PeerID.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.Modes/DownloadModeTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.Modes/HashingModeTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.Modes/MetadataModeTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.Modes/StoppedModeTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.Modes/StoppingModeTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/ConnectionManagerTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/InitialSeedUnchokerTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/PeerExchangeManagerTests.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/TestRig.cs
src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/TestWebSeed.cs
src/Tests/Tests.MonoTorrent.Dht/MonoTorrent.Dht/TaskTests.cs

PeerId objects are now guaranteed to run their disposal logic exactly once, which ensures retries are attempted at the right time.
Additionally, PeerId objects are only created when the session is fully initialised, making it harder to add them to internal lists before everything is ready. This also makes cleanup easier if the connection attempt fails as the only thing which needs to be done is to dispose the `IPeerConnection` object :)

Better handling of incoming and outgoing connections
