- src/MonoTorrent/MonoTorrent.Client/Managers/LocalPeerManager.cs
Previously local peer discovery was only working on the main network interface, this should fix it for having multiple e.g. WiFi and lan
> Update LocalPeerManager.cs to fix Local peer discovery with multiple NICs

- src/MonoTorrent/MonoTorrent.Client/Managers/ConnectionManager.cs
- src/MonoTorrent/MonoTorrent.Client/PeerConnections/PeerId.cs
- src/MonoTorrent/MonoTorrent.Common/IDisposableExtensions.cs
> Fix some async and cleanup issues

- src/MonoTorrent/MonoTorrent.Client/Tracker/TrackerTier.cs
Expose the trackers as a readonly IList.
> [core] Clean up TrackerTier

- src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
Fixes #118 
Now it should not have issues with adding peers from private trackers.
> fixed problem in AddPeerAsync with peers from private trackers

- src/MonoTorrent.Tests/Client/UdpTrackerTests.cs
- src/MonoTorrent.Tests/Tracker/TrackerTest.cs
- src/MonoTorrent/MonoTorrent.Tracker/AnnounceEventArgs.cs
- src/MonoTorrent/MonoTorrent.Tracker/ITrackerItem.cs
- src/MonoTorrent/MonoTorrent.Tracker/PeerEventArgs.cs
- src/MonoTorrent/MonoTorrent.Tracker/SimpleTorrentManager.cs
- src/MonoTorrent/MonoTorrent.Tracker/TimedOutEventArgs.cs
- src/MonoTorrent/MonoTorrent.Tracker/TrackerServer.cs
@justscribe These are the changes I suggested in the other PR. This is an API break, but i think it's one of the final API updates I will be making since the old 0.9 release.
> Update tracker api

- src/MonoTorrent.Tests/MonoTorrent.Client.Modes/HashingModeTests.cs
- src/MonoTorrent.Tests/MonoTorrent.Client.Modes/StartingModeTests.cs
- src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
- src/MonoTorrent/MonoTorrent.Client/Modes/HashingMode.cs
- src/MonoTorrent/MonoTorrent.Client/Modes/StartingMode.cs
- src/MonoTorrent/MonoTorrent/Enums.cs
- src/SampleClient/main.cs
Adds the feature requested in https://github.com/mono/monotorrent/issues/138
> [core] Add the ability to pause hashing

- src/MonoTorrent/MonoTorrent.Client/Modes/HashingMode.cs
- src/MonoTorrent/MonoTorrent.Client/Modes/Mode.cs
Every mode should be using this nowadays!
> [core] Move the CancellationTokenSource to the base class

- src/Directory.Build.props
- src/MonoTorrent/MonoTorrent.csproj
And we can use some of the newer features.
> [core] Update to LangVersion 8.0 as CI supports it

- src/MonoTorrent.Tests/Common/BigEndianBigIntegerTests.cs
- src/MonoTorrent/MonoTorrent.Client.Encryption/EncryptedSocket.cs
- src/MonoTorrent/MonoTorrent.Client.Encryption/PeerAEncryption.cs
- src/MonoTorrent/MonoTorrent.Client.Encryption/PeerBEncryption.cs
- src/MonoTorrent/MonoTorrent.Dht/Bucket.cs
- src/MonoTorrent/MonoTorrent.Dht/NodeId.cs
- src/MonoTorrent/MonoTorrent.Dht/RoutingTable.cs
- src/MonoTorrent/MonoTorrent/BigEndianBigInteger.cs
> Memory perf

- src/MonoTorrent/MonoTorrent.Client.Encryption/EncryptedSocket.cs
- src/MonoTorrent/MonoTorrent.Client.Encryption/EncryptorFactory.cs
Sending/Receiving handshakes should use pooled buffers.
> [core] Use pooled buffers in four more places

- src/MonoTorrent/MonoTorrent.Client.Encryption/EncryptedSocket.cs
This should be a local variable. Note: we cannot use a buffer
from our pool for this as it is converted into a BigInteger.
> [core] Move class level buffers to method level

- src/MonoTorrent/MonoTorrent.csproj
> [core] Bump to ReusableTasks 1.0.0

- src/MonoTorrent/MonoTorrent.Client.Connections/SocketConnection.cs
This was necessary before ReusableTaskCompletionSource<T> was
fully implemented. Now that it's complete, we can remove the
'async' modifier from these methods and just return the
TCS.Task property directly. This means only one continuation
will need to execute instead of two.
> [core] Don't wrap SocketConnection in two ReusableTasks

- src/MonoTorrent/MonoTorrent.Client.Connections/SocketConnection.cs
- src/MonoTorrent/MonoTorrent.Client.Encryption/EncryptedSocket.cs
- src/MonoTorrent/MonoTorrent.Client.Encryption/EncryptorFactory.cs
- src/MonoTorrent/MonoTorrent.Client.Encryption/PeerAEncryption.cs
- src/MonoTorrent/MonoTorrent.Client.Encryption/PeerBEncryption.cs
- src/MonoTorrent/MonoTorrent.Client.Messages/PieceMessage.cs
- src/MonoTorrent/MonoTorrent.Client.PieceWriters/MemoryWriter.cs
- src/MonoTorrent/MonoTorrent.Client/ClientEngine.cs
- src/MonoTorrent/MonoTorrent.Client/Managers/BufferPool.cs
- src/MonoTorrent/MonoTorrent.Client/Managers/ConnectionManager.cs
- src/MonoTorrent/MonoTorrent.Client/Managers/DiskManager.cs
- src/MonoTorrent/MonoTorrent.Client/Modes/Mode.cs
- src/MonoTorrent/MonoTorrent.Client/PeerIO.cs
This is a better description of what the class actually
does.
> [core] Rename BufferManager to BufferPool

- src/MonoTorrent/MonoTorrent.csproj
This new release will throw InvalidTaskReuseException if something
bad occurs, whereas previous releases would throw an
InvalidOperationException.
> [core] Bump ReusableTasks to get better diagnostics

- src/MonoTorrent.Tests/Client/TestRig.cs
- src/MonoTorrent.Tests/Client/TestWebSeed.cs
- src/MonoTorrent/MonoTorrent.Client.Connections/HTTPConnection.cs
- src/MonoTorrent/MonoTorrent.Client.Messages/RequestBundle.cs
- src/MonoTorrent/MonoTorrent.Client/Managers/ConnectionManager.cs
- src/MonoTorrent/MonoTorrent.Client/Managers/PieceManager.cs
- src/MonoTorrent/MonoTorrent.Client/Modes/Mode.cs
- src/MonoTorrent/MonoTorrent.Client/Settings/TorrentSettings.cs
Addresses https://github.com/mono/monotorrent/issues/149
> [core] Re-enable webseeding

- src/MonoTorrent.Tests/Client/HttpTrackerTests.cs
- src/MonoTorrent.Tests/Client/UdpTrackerTests.cs
- src/MonoTorrent/MonoTorrent.Client.Tracker/HTTPTracker.cs
- src/MonoTorrent/MonoTorrent.Client.Tracker/UdpTracker.cs
- src/MonoTorrent/MonoTorrent.Tracker.Listeners/HttpTrackerListener.cs
- src/MonoTorrent/MonoTorrent.Tracker/TrackerServer.cs
Try to track online/offline/invalid status as best we can. Add tests covering all the cases.
> Ensure tracker state is as accurate as we can guess

- src/MonoTorrent/MonoTorrent.Client.PiecePicking/StreamingPiecePicker.cs
- src/MonoTorrent/MonoTorrent.Streaming/DirectStream.cs
- src/MonoTorrent/MonoTorrent.Streaming/HttpStream.cs
- src/MonoTorrent/MonoTorrent.Streaming/IUriStream.cs
- src/MonoTorrent/MonoTorrent.Streaming/LocalStream.cs
- src/MonoTorrent/MonoTorrent.Streaming/StreamProvider.cs
- src/SampleClient/main.cs
This is a prototype which hasn't even been tested yet ;)
> Add a way to stream media while downloading

- src/MonoTorrent/MonoTorrent.Client/LocalPeerDiscovery.cs
The LPD code should take into account the fact that multiple torrents
may announce in a relatively short amount of time. Add batching so
that the LDP announce runs, at most, once a second so we can amortize
the cost of iterating the NICs.
> [core] Add batching to LocalPeerDiscovery.Announce

- src/MonoTorrent/MonoTorrent/ToolBox.cs
Save a fair few allocations when emitting a lot of
async events. Should reduce time spent in the GC in
some artificial benchmarks. Not sure if it'll make
a real world improvement though.
> [core] Reduce allocations invoking events async

- src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
When we're hashing torrents with hundreds or thousands of files
we can update the bitfield more efficiently if we use binary
search to find a matching file.
In addition we can bail out as soon as we find a file which no
longer contains the piece we're interested in, which is a saving
in and of itself.
Partially addresses https://github.com/alanmcgovern/monotorrent/issues/223
> [core] Update bitfields faster when hashing

- src/MonoTorrent.Tests/Client/TestRig.cs
- src/MonoTorrent.Tests/Client/TrackerManagerTests.cs
- src/MonoTorrent.Tests/MonoTorrent.Client.Modes/DownloadModeTests.cs
- src/MonoTorrent.Tests/MonoTorrent.Client.Modes/StartingModeTests.cs
- src/MonoTorrent/MonoTorrent.Client.Tracker/TrackerTier.cs
- src/MonoTorrent/MonoTorrent.Client/ITrackerManager.cs
- src/MonoTorrent/MonoTorrent.Client/Managers/TrackerManager.cs
- src/MonoTorrent/MonoTorrent.Client/Modes/Mode.cs
- src/MonoTorrent/MonoTorrent.Client/Modes/StoppingMode.cs
- src/SampleClient/main.cs
This is the intent of the spec. The fact MonoTorrent did not do
this before is a bug.
Fixes https://github.com/alanmcgovern/monotorrent/issues/250
> [core] Announce to all Tracker Tiers concurrently

- src/MonoTorrent/MonoTorrent.Client/PeerIO.cs
Currently ProtocolUp counter has negative value, and DataUp counter is also probably wrong
> Fixing ProtocolUp counter

- src/MonoTorrent/MonoTorrent.Client.Tracker/AnnounceParameters.cs
- src/MonoTorrent/MonoTorrent.Client.Tracker/ScrapeParameters.cs
This also adds an internal WithCancellationToken
method.
I should do it as two commits... but...
> [core] Simplify [Announce|Scrape]Parameters cloning

- src/MonoTorrent.Tests/Client/DiskManagerTests.cs
- src/MonoTorrent/MonoTorrent.Client/Managers/DiskManager.cs
Ensure the incremental hasher takes the torrent manager
as well as the piece index into account.
Ensure we don't have unexpected interaction between
multiple concurrent downloads.
> [core] Ensure data is not mixed between torrents

- src/MonoTorrent/MonoTorrent.Client.Connections/SocketConnection.cs
> Public SocketConnection for logging

- src/MonoTorrent.Tests/Common/MagnetLinkTest.cs
- src/MonoTorrent/MonoTorrent/MagnetLink.cs
> Allow hybrid v1/v2 magnet links

- src/MonoTorrent/MonoTorrent.Client/LocalPeerDiscovery.cs
Added code, which joins multicast group on each network interface with IP address, this resolves case, when you seed from computer with multiple network cards and leeches connect to you after long timeout (at least 5min)
> fix local peer discovery on systems with multiple network interfaces

- src/MonoTorrent.Tests/Client/BlockingWriter.cs
- src/MonoTorrent.Tests/Client/MemoryWriterTests.cs
- src/MonoTorrent.Tests/MonoTorrent.Client.Modes/DownloadModeTests.cs
- src/MonoTorrent.Tests/TaskExtensions.cs
- src/MonoTorrent/MonoTorrent.Client.PieceWriters/MemoryWriter.cs
- src/MonoTorrent/MonoTorrent.Client/Managers/DiskManager.cs
- src/MonoTorrent/MonoTorrent.Client/Modes/DownloadMode.cs
Flush data before entering seeding mode
> Flush before seeding

- src/MonoTorrent/MonoTorrent.Client.Encryption/EncryptionType.cs
Fixed ArrayIndexOutOfBound exception when peer allowedEncryption list is empty
> EncryptionType ArrayIndexOutOfBound exception fix

- src/MonoTorrent/MonoTorrent.Client/ClientEngine.cs
- src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs
Make some fields readonly. Remove unused constructors. Misc related cleanups.
> Cleanup constructors

- src/MonoTorrent.Client/MonoTorrent.Client/Managers/ConnectionMonitor.cs
Add docs covering each property, describing exactly how the value is calculated.
Addresses https://github.com/alanmcgovern/monotorrent/issues/488
> [core] Improve the documentation for ConnectionMonitor

- src/MonoTorrent/MonoTorrent/Torrent.cs
This is a regression that appeared in v1.0.28.
> [core] Properly initialise Torrent.TorrentPath

- src/MonoTorrent/MonoTorrent.Client/ClientEngine.cs
Now it's threadsafe when users call StartAsync/StopAsync on multiple different `TorrentManager` instances concurrently.
Fixes https://github.com/alanmcgovern/monotorrent/issues/499
> [core] Ensure the dht node cahe is written safely

- src/MonoTorrent.Client/MonoTorrent.Client.Modes/HashingMode.cs
- src/MonoTorrent.Client/MonoTorrent.Client.Modes/Mode.cs
- src/MonoTorrent.Client/MonoTorrent.Client/ClientEngine.cs
- src/MonoTorrent.Client/MonoTorrent.Client/Managers/ConnectionManager.cs
- src/MonoTorrent.Client/MonoTorrent.Client/Managers/DiskManager.cs
- src/MonoTorrent.Client/MonoTorrent.Client/Managers/ListenManager.cs
- src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentManager.cs
- src/MonoTorrent.Client/MonoTorrent/IPieceHashes.cs
- src/MonoTorrent.Client/MonoTorrent/MerkleHash.cs
- src/MonoTorrent.Client/MonoTorrent/PieceHash.cs
- src/MonoTorrent.Client/MonoTorrent/PieceHashes.cs
- src/MonoTorrent.Client/MonoTorrent/PieceHashesV2.cs
- src/MonoTorrent.Client/MonoTorrent/ReadOnlyPieceHash.cs
- src/MonoTorrent.Client/MonoTorrent/Torrent.cs
- src/MonoTorrent.Messages/MonoTorrent.Messages.Peer/HandshakeMessage.cs
- src/MonoTorrent/MonoTorrent/InfoHashes.cs
- src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.Modes/HashingModeTests.cs
- src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/DiskManagerTests.cs
- src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/FastResumeTests.cs
- src/Tests/Tests.MonoTorrent.Client/MonoTorrent/HashesTests.cs
- src/Tests/Tests.MonoTorrent.Client/MonoTorrent/TorrentV2Test.cs
Implement the next phase of bep52.
We can download V2 torrents now!
> Download a v2 torrent

- src/MonoTorrent.Client/MonoTorrent/Torrent.cs
This *should* solve #517, but I don't know C# 🙃
> Disregard certain path segments

- src/MonoTorrent.Client/MonoTorrent/MagnetLink.cs
- src/MonoTorrent/MonoTorrent/InfoHash.cs
- src/Tests/Tests.MonoTorrent.Client/MonoTorrent/MagnetLinkTest.cs
Fixes alanmcgovern/monotorrent#520
> V2 only magnetlink support

- src/MonoTorrent.Client/MonoTorrent.Client.Modes/Mode.cs
- src/MonoTorrent.Client/MonoTorrent.Client.Modes/PieceHashesMode.cs
- src/MonoTorrent.Client/MonoTorrent.Client/Managers/DiskManager.cs
- src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentFileInfo.cs
- src/MonoTorrent.Client/MonoTorrent/IPieceHashes.cs
- src/MonoTorrent.Client/MonoTorrent/MerkleHash.cs
- src/MonoTorrent.Client/MonoTorrent/MerkleLayers.cs
- src/MonoTorrent.Client/MonoTorrent/PieceHashes.cs
- src/MonoTorrent.Client/MonoTorrent/PieceHashesV1.cs
- src/MonoTorrent.Client/MonoTorrent/PieceHashesV2.cs
- src/MonoTorrent.Client/MonoTorrent/ReadOnlyMerkleLayers.cs
- src/MonoTorrent.Client/MonoTorrent/Torrent.cs
- src/MonoTorrent.Client/MonoTorrent/TorrentCreator.cs
- src/MonoTorrent.Client/MonoTorrent/TorrentFile.cs
- src/MonoTorrent.Messages/MonoTorrent.Messages.Peer/HashRejectMessage.cs
- src/MonoTorrent.Messages/MonoTorrent.Messages.Peer/HashRequestMessage.cs
- src/MonoTorrent.Messages/MonoTorrent.Messages.Peer/HashesMessage.cs
- src/MonoTorrent/MonoTorrent/MerkleRoot.cs
- src/Tests/Tests.MonoTorrent.Client/MonoTorrent/MerkleTests.cs
- src/Tests/Tests.MonoTorrent.Client/MonoTorrent/TorrentV2Test.cs
- src/Tests/Tests.MonoTorrent.Messages/StandardMessageTests.cs
Add the core classes used to create and operate merkle trees
This would've been better as a series of PRs, but splitting it
up is more of a pain than it's worth.
> [core] Add merkle tree support

- azure-pipelines.yml
Migrate to a yaml based solution
> Set up CI with Azure Pipelines yaml

- src/MonoTorrent.Client/MonoTorrent.Client.Modes/StartingMode.cs
- src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentManager.cs
- src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/ClientEngineTests.cs
Fixes https://github.com/alanmcgovern/monotorrent/issues/560
I'll split this up a bit and add a few more tests in other places!
> More fixes for empty files

- src/MonoTorrent.sln
- src/Tests/Tests.MonoTorrent.IntegrationTests/IntegrationTests.cs
- src/Tests/Tests.MonoTorrent.IntegrationTests/Tests.MonoTorrent.IntegrationTests.csproj
Here's the integration tests I previously copy/pasted on #560. I also added more to show the issue with implicit vs explicit hash check in #565.
After the changes from #565, these should all pass
This was originally in #566, but reopened to master instead of the deleted branch.
Thanks as always for a great library!
> Integration tests

- src/MonoTorrent.Client/MonoTorrent.Client.Modes/Mode.cs
- src/MonoTorrent.Client/MonoTorrent.Connections/HttpPeerConnection.cs
- src/Tests/Directory.Build.props
- src/Tests/Tests.MonoTorrent.IntegrationTests/IntegrationTests.cs
- src/Tests/Tests.MonoTorrent.IntegrationTests/Tests.MonoTorrent.IntegrationTests.csproj
I think there may be a problem downloading via web seeds. Here's an integration test to illustrate the issue. I think the issue is downloading the last piece of the torrent. On the "bigger" 30KB files test, it downloads the full 30KB of the 1st file, but 16KB of 30KB in the 2nd.
Thanks for your help with this! And please let me know if PRing like this is how you'd like issues like this raised.
> Web Seed Integration Tests

- src/Tests/Tests.MonoTorrent.IntegrationTests/IntegrationTests.cs
If the response is not closed then the connection will be treated as failed only after the 30 second timeout is hit.
The `WebSeedDownload_V1V2_RetryWebSeeder` test took 32 seconds to execute before this change. Now it takes 2 seconds.
> [tests] Close the response after writing the status code

- azure-pipelines.yml
Maybe this will fix tests in CI again?
> Specify 'Release' configurations properly

- src/MonoTorrent.Connections/MonoTorrent.Connections.Peer/SocketPeerConnection.cs
- src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/SocketConnectionTests.cs
We need to wrap the address in square brackets here
> [core] Fix creating ipv6 uris

- src/MonoTorrent.Client/MonoTorrent.Client.Modes/Mode.cs
- src/MonoTorrent.Client/MonoTorrent.Client/Managers/PeerExchangeManager.cs
- src/MonoTorrent.Messages/MonoTorrent.Messages.Peer.Libtorrent/PeerExchangeMessage.cs
- src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client.Modes/DownloadModeTests.cs
- src/Tests/Tests.MonoTorrent.Messages/PeerExchangeMessageTests.cs
ipv4 and ipv6 peers are captured in the peer exchange manager, with the ipv4 and ipv6 fields populated in the peer exchange message too. These fields are parsed and used to populate the peer tables now.
> [core] Add full ipv6 support for PeerExchange

- src/MonoTorrent.Client/MonoTorrent.Client.Tracker/TrackerRequestFactory.cs
- src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentManager.cs
- src/MonoTorrent.Trackers/MonoTorrent.Client.Messages.UdpTracker/AnnounceMessage.cs
- src/MonoTorrent.Trackers/MonoTorrent.Connections.Tracker/HTTPTrackerConnection.cs
- src/MonoTorrent.Trackers/MonoTorrent.Connections.Tracker/UdpTrackerConnection.cs
- src/MonoTorrent/MonoTorrent.TrackerServer/AnnounceRequest.cs
- src/MonoTorrent/MonoTorrent.Trackers/AnnounceRequest.cs
- src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/HttpTrackerTests.cs
- src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/MultiProtocolHttpTrackerTests.cs
- src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/MultiProtocolUdpTrackerTests.cs
- src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/UdpTrackerTests.cs
- src/Tests/Tests.MonoTorrent.Client/MonoTorrent.TrackerServer/TrackerTests.cs
- src/Tests/Tests.MonoTorrent.IntegrationTests/IntegrationTests.cs
Finalize ipv6 support by adding end-to-end tests using ipv6.
> Integration tests ipv6

- src/MonoTorrent.Trackers/MonoTorrent.Connections.TrackerServer/HttpTrackerListener.cs
- src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/HttpTrackerTests.cs
When hosting a tracker, an unexpected exception looks like it could cause an empty response to be sent to the client who announced/scraped, while also setting a '200' success code.
Let's be really explicit here and log any unexpected errors while also return an internal server error (status code 500) if something unexpected really does occur.
Might help diagnose https://github.com/alanmcgovern/monotorrent/issues/613
> [core] Add logging when handling requests in the Tracker server

- .gitignore
- azure-pipelines.yml
- coverage.bat
- src/Tests/Directory.Build.targets
This is much easier than using VSTS for coverage.
> Add code coverage tooling

- src/MonoTorrent.Client/MonoTorrent.Client.csproj
Not sure how I missed that. I checked the list so many times.
Addresses https://github.com/alanmcgovern/monotorrent/issues/666
> Ensure ReusableTasks is a nuget dependency

- src/MonoTorrent.Client/MonoTorrent.Client.Modes/Mode.cs
This fixes a race condition where peers would sometimes get stuck while fetching bittorrent v2 hashes, depending on the timing of when the first request was made and then the final part of the handshake completed.
If requests were enqueued early, everything was fine. If requests were queued late, then nothing would kick off the queue consumer and enqueued messages would be left pending until the peer timed out, or until a KeepAlive message was sent which would unblock the queue.
Addresses issues like https://github.com/alanmcgovern/monotorrent/issues/672
> Ensure pending messages are processed from the send queue regularly

- src/MonoTorrent.Client/MonoTorrent.Client/Managers/TorrentManager.cs
- src/Tests/Tests.MonoTorrent.Client/MonoTorrent.Client/FastResumeTests.cs
FastResume data stores one of the two infohashes - for hybrid torrents it stores the v1 hash, similar to how handshakes are always sent using the v1 hash.
However, the code which loaded the resulting data from disk didn't account for this and expected to see both the v1 and v2 hash before it would allow the fast resume data to load.
Potentially address part of https://github.com/alanmcgovern/monotorrent/issues/676
> Fix issues saving/loading fastresume for hybrid torrents
